"""`hermes t3 connect` enrollment command."""

from __future__ import annotations

import argparse
import asyncio
import os
import sys

from .connection import ConnectionRejected, enroll_once, websocket_url

URL_ENV = "HERMES_T3_GATEWAY_URL"
INSTANCE_ID_ENV = "HERMES_T3_GATEWAY_INSTANCE_ID"
CREDENTIAL_ENV = "HERMES_T3_GATEWAY_CREDENTIAL"
NICKNAME_ENV = "HERMES_T3_GATEWAY_NICKNAME"


def _hermes_version() -> str:
    try:
        from hermes_cli import __version__

        return str(__version__)
    except Exception:  # noqa: BLE001 - version discovery must not block enrollment
        return "unknown"


def register_cli(parser: argparse.ArgumentParser) -> None:
    commands = parser.add_subparsers(dest="t3_command")
    connect = commands.add_parser(
        "connect",
        help="Pair this Hermes process with a named T3 Code provider instance",
    )
    connect.add_argument(
        "--url",
        required=True,
        help="T3 browser origin or explicit ws(s) gateway URL",
    )
    connect.add_argument(
        "--token",
        required=True,
        help="Short-lived, one-time enrollment token generated by T3 Code",
    )
    connect.set_defaults(func=t3_command)

    status = commands.add_parser("status", help="Show local T3 enrollment state")
    status.set_defaults(func=t3_command)


def t3_command(args) -> None:
    command = getattr(args, "t3_command", None)
    if command == "status":
        _print_status()
        return
    if command != "connect":
        print("Usage: hermes t3 connect --url <t3-url> --token <one-time-token>")
        return

    url = str(getattr(args, "url", "") or "").strip()
    token = str(getattr(args, "token", "") or "").strip()
    try:
        normalized_url = websocket_url(url)
        accepted = asyncio.run(
            enroll_once(
                url=normalized_url,
                token=token,
                hermes_version=_hermes_version(),
            )
        )
    except ConnectionRejected as exc:
        print(f"✗ T3 enrollment rejected ({exc.code}): {exc}")
        raise SystemExit(1) from exc
    except Exception as exc:
        print(f"✗ Could not enroll with T3 Code: {exc}")
        raise SystemExit(1) from exc

    values = {
        URL_ENV: normalized_url,
        INSTANCE_ID_ENV: str(accepted["instanceId"]),
        CREDENTIAL_ENV: str(accepted["credential"]),
        NICKNAME_ENV: str(accepted.get("nickname") or "Hermes"),
    }
    try:
        from hermes_cli.config import get_env_path, save_env_value

        for key, value in values.items():
            save_env_value(key, value)
        env_path = get_env_path()
    except Exception as exc:
        print(f"✗ Enrollment succeeded, but credentials could not be saved: {exc}")
        print("  The credential was not printed. Revoke and re-enroll this instance.")
        raise SystemExit(1) from exc

    # Mirror the newly written values into this process for status output and
    # tests. A running gateway still needs a restart to construct the adapter.
    os.environ.update(values)
    print(f'✓ Connected Hermes to T3 Code as "{values[NICKNAME_ENV]}"')
    print(f"  Instance: {values[INSTANCE_ID_ENV]}")
    print(f"  Gateway:  {normalized_url}")
    print(f"  Saved the credential securely in {env_path} (value hidden).")
    print("  Restart `hermes gateway` to activate the connection.")


def _print_status() -> None:
    url = os.environ.get(URL_ENV, "").strip()
    instance_id = os.environ.get(INSTANCE_ID_ENV, "").strip()
    credential = os.environ.get(CREDENTIAL_ENV, "").strip()
    nickname = os.environ.get(NICKNAME_ENV, "").strip() or "Hermes"
    if not (url and instance_id and credential):
        print("T3 Code: not enrolled")
        print("Run: hermes t3 connect --url <t3-url> --token <one-time-token>")
        return
    print(f"T3 Code: enrolled as {nickname}")
    print(f"  Instance: {instance_id}")
    print(f"  Gateway:  {url}")
    print("  Credential: configured (hidden)")


if __name__ == "__main__":  # pragma: no cover - executable fallback
    parser = argparse.ArgumentParser(prog="python -m hermes_t3_gateway.cli")
    register_cli(parser)
    parsed = parser.parse_args()
    if not hasattr(parsed, "func"):
        parser.print_help()
        sys.exit(2)
    parsed.func(parsed)
