import type { ThemeDocument } from "@t3tools/contracts";

/**
 * Built-in theme definitions. Each theme provides seed colors that are used
 * to derive the full set of CSS variables for the UI.
 */
export const BUILT_IN_THEMES = [
  // T3 branded themes (app defaults)
  {
    id: "t3-light",
    name: "T3 Light",
    mode: "light",
    accentSeed: "#4f46e5",
    backgroundSeed: "#ffffff",
    foregroundSeed: "#262626",
    neutralSeed: "#737373",
    semanticSlots: {},
  },
  {
    id: "t3-dark",
    name: "T3 Dark",
    mode: "dark",
    accentSeed: "#6366f1",
    backgroundSeed: "#0d0d0d",
    foregroundSeed: "#f5f5f5",
    neutralSeed: "#737373",
    semanticSlots: {},
  },
  // Community themes
  {
    id: "builtin-tango-light",
    name: "Builtin Tango Light",
    mode: "light",
    accentSeed: "#3465a4",
    backgroundSeed: "#ffffff",
    foregroundSeed: "#2e3434",
    neutralSeed: "#555753",
    semanticSlots: {},
  },
  {
    id: "solarized-light",
    name: "Solarized Light",
    mode: "light",
    accentSeed: "#268bd2",
    backgroundSeed: "#fdf6e3",
    foregroundSeed: "#657b83",
    neutralSeed: "#93a1a1",
    semanticSlots: {},
  },
  {
    id: "one-light",
    name: "One Light",
    mode: "light",
    accentSeed: "#4078f2",
    backgroundSeed: "#fafafa",
    foregroundSeed: "#383a42",
    neutralSeed: "#696c77",
    semanticSlots: {},
  },
  {
    id: "catppuccin-latte",
    name: "Catppuccin Latte",
    mode: "light",
    accentSeed: "#1e66f5",
    backgroundSeed: "#eff1f5",
    foregroundSeed: "#4c4f69",
    neutralSeed: "#6c6f85",
    semanticSlots: {},
  },
  {
    id: "github-light",
    name: "GitHub Light",
    mode: "light",
    accentSeed: "#0366d6",
    backgroundSeed: "#ffffff",
    foregroundSeed: "#24292e",
    neutralSeed: "#959da5",
    semanticSlots: {},
  },
  {
    id: "rose-pine-dawn",
    name: "Rose Pine Dawn",
    mode: "light",
    accentSeed: "#56949f",
    backgroundSeed: "#faf4ed",
    foregroundSeed: "#575279",
    neutralSeed: "#9893a5",
    semanticSlots: {},
  },
  {
    id: "gruvbox-light",
    name: "Gruvbox Light",
    mode: "light",
    accentSeed: "#458588",
    backgroundSeed: "#fbf1c7",
    foregroundSeed: "#3c3836",
    neutralSeed: "#928374",
    semanticSlots: {},
  },
  {
    id: "tokyo-night-light",
    name: "Tokyo Night Light",
    mode: "light",
    accentSeed: "#34548a",
    backgroundSeed: "#d5d6db",
    foregroundSeed: "#343b58",
    neutralSeed: "#9699a3",
    semanticSlots: {},
  },
  {
    id: "everforest-light",
    name: "Everforest Light",
    mode: "light",
    accentSeed: "#3a94c5",
    backgroundSeed: "#fdf6e3",
    foregroundSeed: "#5c6a72",
    neutralSeed: "#939f91",
    semanticSlots: {},
  },
  {
    id: "ghostty-default-style-dark",
    name: "Ghostty Default Style Dark",
    mode: "dark",
    accentSeed: "#81a2be",
    backgroundSeed: "#282c34",
    foregroundSeed: "#ffffff",
    neutralSeed: "#666666",
    semanticSlots: {},
  },
  {
    id: "tango-dark",
    name: "Tango Dark",
    mode: "dark",
    accentSeed: "#3465a4",
    backgroundSeed: "#000000",
    foregroundSeed: "#d3d7cf",
    neutralSeed: "#555753",
    semanticSlots: {},
  },
  {
    id: "homebrew",
    name: "Homebrew",
    mode: "dark",
    accentSeed: "#0000b2",
    backgroundSeed: "#000000",
    foregroundSeed: "#00ff00",
    neutralSeed: "#666666",
    semanticSlots: {},
  },
  {
    id: "snazzy",
    name: "Snazzy",
    mode: "dark",
    accentSeed: "#57c7ff",
    backgroundSeed: "#282a36",
    foregroundSeed: "#eff0eb",
    neutralSeed: "#686868",
    semanticSlots: {},
  },
  {
    id: "dracula",
    name: "Dracula",
    mode: "dark",
    accentSeed: "#bd93f9",
    backgroundSeed: "#282a36",
    foregroundSeed: "#f8f8f2",
    neutralSeed: "#6272a4",
    semanticSlots: {},
  },
  {
    id: "one-dark",
    name: "One Dark",
    mode: "dark",
    accentSeed: "#61afef",
    backgroundSeed: "#282c34",
    foregroundSeed: "#abb2bf",
    neutralSeed: "#5c6370",
    semanticSlots: {},
  },
  {
    id: "nord",
    name: "Nord",
    mode: "dark",
    accentSeed: "#81a1c1",
    backgroundSeed: "#2e3440",
    foregroundSeed: "#d8dee9",
    neutralSeed: "#4c566a",
    semanticSlots: {},
  },
  {
    id: "monokai",
    name: "Monokai",
    mode: "dark",
    accentSeed: "#66d9ef",
    backgroundSeed: "#272822",
    foregroundSeed: "#f8f8f2",
    neutralSeed: "#75715e",
    semanticSlots: {},
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    mode: "dark",
    accentSeed: "#7aa2f7",
    backgroundSeed: "#1a1b26",
    foregroundSeed: "#c0caf5",
    neutralSeed: "#414868",
    semanticSlots: {},
  },
  {
    id: "gruvbox-dark",
    name: "Gruvbox Dark",
    mode: "dark",
    accentSeed: "#458588",
    backgroundSeed: "#282828",
    foregroundSeed: "#ebdbb2",
    neutralSeed: "#928374",
    semanticSlots: {},
  },
  {
    id: "catppuccin-mocha",
    name: "Catppuccin Mocha",
    mode: "dark",
    accentSeed: "#89b4fa",
    backgroundSeed: "#1e1e2e",
    foregroundSeed: "#cdd6f4",
    neutralSeed: "#585b70",
    semanticSlots: {},
  },
  {
    id: "solarized-dark",
    name: "Solarized Dark",
    mode: "dark",
    accentSeed: "#268bd2",
    backgroundSeed: "#002b36",
    foregroundSeed: "#839496",
    neutralSeed: "#586e75",
    semanticSlots: {},
  },
  {
    id: "material-dark",
    name: "Material Dark",
    mode: "dark",
    accentSeed: "#82aaff",
    backgroundSeed: "#263238",
    foregroundSeed: "#eeffff",
    neutralSeed: "#546e7a",
    semanticSlots: {},
  },
  {
    id: "ayu-dark",
    name: "Ayu Dark",
    mode: "dark",
    accentSeed: "#53bdfa",
    backgroundSeed: "#0a0e14",
    foregroundSeed: "#b3b1ad",
    neutralSeed: "#686868",
    semanticSlots: {},
  },
  {
    id: "nightfox",
    name: "Nightfox",
    mode: "dark",
    accentSeed: "#719cd6",
    backgroundSeed: "#192330",
    foregroundSeed: "#cdcecf",
    neutralSeed: "#575860",
    semanticSlots: {},
  },
  {
    id: "kanagawa",
    name: "Kanagawa",
    mode: "dark",
    accentSeed: "#7e9cd8",
    backgroundSeed: "#1f1f28",
    foregroundSeed: "#dcd7ba",
    neutralSeed: "#727169",
    semanticSlots: {},
  },
  {
    id: "rose-pine",
    name: "Rose Pine",
    mode: "dark",
    accentSeed: "#9ccfd8",
    backgroundSeed: "#191724",
    foregroundSeed: "#e0def4",
    neutralSeed: "#6e6a86",
    semanticSlots: {},
  },
  {
    id: "everforest-dark",
    name: "Everforest Dark",
    mode: "dark",
    accentSeed: "#7fbbb3",
    backgroundSeed: "#2d353b",
    foregroundSeed: "#d3c6aa",
    neutralSeed: "#697379",
    semanticSlots: {},
  },
  {
    id: "palenight",
    name: "Palenight",
    mode: "dark",
    accentSeed: "#82aaff",
    backgroundSeed: "#292d3e",
    foregroundSeed: "#a6accd",
    neutralSeed: "#676e95",
    semanticSlots: {},
  },
  {
    id: "horizon-dark",
    name: "Horizon Dark",
    mode: "dark",
    accentSeed: "#26bbd9",
    backgroundSeed: "#1c1e26",
    foregroundSeed: "#e0e0e0",
    neutralSeed: "#6c6f93",
    semanticSlots: {},
  },
  {
    id: "night-owl",
    name: "Night Owl",
    mode: "dark",
    accentSeed: "#82aaff",
    backgroundSeed: "#011627",
    foregroundSeed: "#d6deeb",
    neutralSeed: "#575656",
    semanticSlots: {},
  },
] as const satisfies ReadonlyArray<ThemeDocument>;
