// @effect-diagnostics nodeBuiltinImport:off
import * as NodeFS from "node:fs";
import * as NodeOS from "node:os";
import * as NodePath from "node:path";

import { describe, expect, it } from "@effect/vitest";

import { readTranscriptRecords } from "./usageTranscriptReader.ts";

function rolloutLine(
  type: string,
  payload: Record<string, unknown>,
  timestamp = "2026-08-01T15:21:00.000Z",
  ordinal?: number,
): string {
  return JSON.stringify(
    ordinal === undefined
      ? { timestamp, type, payload }
      : {
          timestamp,
          type,
          payload,
          ordinal,
        },
  );
}

function tokenCount(
  inputTokens: number,
  outputTokens: number,
  options: { readonly timestamp?: string; readonly ordinal?: number } = {},
): string {
  return rolloutLine(
    "event_msg",
    {
      type: "token_count",
      info: {
        last_token_usage: {
          input_tokens: inputTokens,
          cached_input_tokens: 0,
          output_tokens: outputTokens,
          reasoning_output_tokens: 0,
        },
      },
    },
    options.timestamp,
    options.ordinal,
  );
}

async function readCodexTranscript(lines: readonly string[]) {
  const tempDir = NodeFS.mkdtempSync(NodePath.join(NodeOS.tmpdir(), "t3-usage-codex-fork-"));
  const transcriptPath = NodePath.join(tempDir, "rollout.jsonl");
  try {
    NodeFS.writeFileSync(transcriptPath, lines.join("\n"));
    const records = await readTranscriptRecords(transcriptPath, "codex");
    if (records === null) throw new Error("test transcript could not be read");
    return records;
  } finally {
    NodeFS.rmSync(tempDir, { recursive: true, force: true });
  }
}

describe("readTranscriptRecords", () => {
  it("counts only usage generated by a forked Codex child", async () => {
    const parentSessionId = "019fb928-a095-7123-9302-8e831bc95a48";
    const childSessionId = "019fbdea-0b40-7472-92c5-6972853285b6";
    const replayedParentTurnId = "019fb928-a14b-7cc3-8445-a15cb0653400";
    // Same UUID-v7 millisecond as the child session. Subagent rollouts announce
    // this turn with task_started; the UUID's random tail cannot order it.
    const childTurnId = "019fbdea-0b40-7e13-8539-71ce72d0987f";

    const records = await readCodexTranscript([
      rolloutLine("session_meta", {
        id: childSessionId,
        thread_source: "subagent",
        source: {
          subagent: { thread_spawn: { parent_thread_id: parentSessionId, depth: 1 } },
        },
      }),
      rolloutLine("session_meta", { id: parentSessionId, source: "interactive" }),
      rolloutLine("event_msg", {
        type: "task_started",
        turn_id: replayedParentTurnId,
      }),
      rolloutLine("turn_context", {
        turn_id: replayedParentTurnId,
        model: "gpt-5.6-sol",
      }),
      tokenCount(100, 10),
      rolloutLine("event_msg", { type: "task_started", turn_id: childTurnId }),
      rolloutLine("turn_context", { turn_id: childTurnId, model: "gpt-5.6-sol" }),
      tokenCount(100, 10),
      tokenCount(20, 2),
    ]);

    expect(records).toHaveLength(1);
    expect(records[0]?.sessionId).toBe(childSessionId);
    expect(records[0]?.totals).toEqual({
      uncachedInputTokens: 20,
      cachedInputTokens: 0,
      cacheCreationTokens: 0,
      outputTokens: 2,
      reasoningTokens: 0,
    });
  });

  it("does not treat a copied turn_context without a turn ID as child history", async () => {
    const parentSessionId = "019fb928-a095-7123-9302-8e831bc95a48";
    const childSessionId = "019fbdea-0b40-7472-92c5-6972853285b6";
    const childTurnId = "019fbdea-0b40-7e13-8539-71ce72d0987f";

    const records = await readCodexTranscript([
      rolloutLine("session_meta", {
        id: childSessionId,
        source: {
          subagent: { thread_spawn: { parent_thread_id: parentSessionId, depth: 1 } },
        },
      }),
      rolloutLine("session_meta", { id: parentSessionId }),
      rolloutLine("turn_context", { model: "gpt-5.6-sol" }),
      tokenCount(100, 10),
      rolloutLine("event_msg", { type: "task_started", turn_id: childTurnId }),
      rolloutLine("turn_context", { turn_id: childTurnId, model: "gpt-5.6-sol" }),
      tokenCount(20, 2),
    ]);

    expect(records).toHaveLength(1);
    expect(records[0]?.sessionId).toBe(childSessionId);
    expect(records[0]?.totals.outputTokens).toBe(2);
  });

  it("uses metadata time and task_started to identify a child with legacy IDs", async () => {
    const parentSessionId = "parent-session";
    const childSessionId = "child-session";
    const ambiguousParentTurnId = "ambiguous-parent-turn";
    const parentTurnId = "parent-turn";
    const childTurnId = "child-turn";

    const records = await readCodexTranscript([
      rolloutLine("session_meta", {
        id: childSessionId,
        parent_thread_id: parentSessionId,
      }),
      rolloutLine("session_meta", { id: parentSessionId }),
      rolloutLine("turn_context", {
        turn_id: ambiguousParentTurnId,
        model: "gpt-5.6-sol",
      }),
      tokenCount(80, 8),
      rolloutLine("event_msg", {
        type: "task_started",
        turn_id: parentTurnId,
        started_at: 1_785_597_600,
      }),
      rolloutLine("turn_context", { turn_id: parentTurnId, model: "gpt-5.6-sol" }),
      tokenCount(100, 10),
      rolloutLine("event_msg", {
        type: "task_started",
        turn_id: childTurnId,
        started_at: 1_785_597_661,
      }),
      rolloutLine("turn_context", { turn_id: childTurnId, model: "gpt-5.6-sol" }),
      tokenCount(20, 2),
    ]);

    expect(records).toHaveLength(1);
    expect(records[0]?.sessionId).toBe(childSessionId);
    expect(records[0]?.totals.outputTokens).toBe(2);
  });

  it("treats a same-second legacy task start as ambiguous", async () => {
    const parentSessionId = "parent-session";
    const childSessionId = "child-session";
    const parentTurnId = "parent-turn";
    const childTurnId = "child-turn";

    const records = await readCodexTranscript([
      rolloutLine(
        "session_meta",
        { id: childSessionId, parent_thread_id: parentSessionId },
        "2026-08-01T15:21:00.900Z",
      ),
      rolloutLine("session_meta", { id: parentSessionId }, "2026-08-01T15:20:00.000Z"),
      rolloutLine(
        "event_msg",
        { type: "task_started", turn_id: parentTurnId, started_at: 1_785_597_660 },
        "2026-08-01T15:21:00.100Z",
      ),
      rolloutLine(
        "turn_context",
        { turn_id: parentTurnId, model: "gpt-5.6-sol" },
        "2026-08-01T15:21:00.200Z",
      ),
      tokenCount(100, 10, { timestamp: "2026-08-01T15:21:00.300Z" }),
      rolloutLine(
        "event_msg",
        { type: "task_started", turn_id: childTurnId, started_at: 1_785_597_661 },
        "2026-08-01T15:21:01.000Z",
      ),
      rolloutLine(
        "turn_context",
        { turn_id: childTurnId, model: "gpt-5.6-sol" },
        "2026-08-01T15:21:01.100Z",
      ),
      tokenCount(20, 2, { timestamp: "2026-08-01T15:21:01.200Z" }),
    ]);

    expect(records).toHaveLength(1);
    expect(records[0]?.sessionId).toBe(childSessionId);
    expect(records[0]?.totals.outputTokens).toBe(2);
  });

  it("uses the paginated child-history boundary when present", async () => {
    const parentSessionId = "019fb928-a095-7123-9302-8e831bc95a48";
    const childSessionId = "019fbdea-0b40-7472-92c5-6972853285b6";

    const records = await readCodexTranscript([
      rolloutLine(
        "session_meta",
        {
          id: childSessionId,
          forked_from_id: parentSessionId,
          history_mode: "paginated",
          subagent_history_start_ordinal: 5,
        },
        undefined,
        0,
      ),
      // The explicit ordinal boundary wins over UUID timing. This turn ID
      // looks newer than the child but still belongs to inherited history.
      rolloutLine(
        "turn_context",
        { turn_id: "019fbdeb-0000-7000-8000-000000000001", model: "gpt-5.6-sol" },
        undefined,
        3,
      ),
      tokenCount(100, 10, { ordinal: 4 }),
      // A fractional ordinal cannot prove that this copied parent turn crossed
      // the boundary. Its older UUID remains the applicable evidence.
      rolloutLine(
        "turn_context",
        { turn_id: "019fb928-a14b-7cc3-8445-a15cb0653400", model: "gpt-5.6-sol" },
        undefined,
        5.5,
      ),
      tokenCount(50, 5, { ordinal: 5.5 }),
      rolloutLine("turn_context", { turn_id: "child-turn", model: "gpt-5.6-sol" }, undefined, 5),
      tokenCount(20, 2, { ordinal: 6 }),
    ]);

    expect(records).toHaveLength(1);
    expect(records[0]?.sessionId).toBe(childSessionId);
    expect(records[0]?.totals.outputTokens).toBe(2);
  });

  it("does not use legacy fork evidence when paginated ordinals are invalid", async () => {
    const parentSessionId = "019fb928-a095-7123-9302-8e831bc95a48";
    const childSessionId = "019fbdea-0b40-7472-92c5-6972853285b6";
    const childTurnId = "019fbdea-0b40-7e13-8539-71ce72d0987f";

    const records = await readCodexTranscript([
      rolloutLine(
        "session_meta",
        {
          id: childSessionId,
          forked_from_id: parentSessionId,
          history_mode: "paginated",
          subagent_history_start_ordinal: 5,
        },
        undefined,
        0,
      ),
      // A newer UUID cannot replace the authoritative ordinal boundary when
      // the copied record's ordinal is malformed.
      rolloutLine(
        "turn_context",
        { turn_id: "019fbdeb-0000-7000-8000-000000000001", model: "gpt-5.6-sol" },
        undefined,
        5.5,
      ),
      tokenCount(100, 10, { ordinal: 5.5 }),
      // Nor can child-looking task evidence without an ordinal open a
      // paginated rollout's gate.
      rolloutLine("event_msg", { type: "task_started", turn_id: childTurnId }),
      rolloutLine("turn_context", { turn_id: childTurnId, model: "gpt-5.6-sol" }),
      tokenCount(50, 5),
      rolloutLine("turn_context", { turn_id: "child-turn", model: "gpt-5.6-sol" }, undefined, 5),
      tokenCount(20, 2, { ordinal: 6 }),
    ]);

    expect(records).toHaveLength(1);
    expect(records[0]?.sessionId).toBe(childSessionId);
    expect(records[0]?.totals.outputTokens).toBe(2);
  });

  it("keeps a human fork's same-millisecond child turn without task_started", async () => {
    const parentSessionId = "019fb928-a095-7123-9302-8e831bc95a48";
    const childSessionId = "019fbdea-0b40-7472-92c5-6972853285b6";
    const records = await readCodexTranscript([
      rolloutLine("session_meta", {
        id: childSessionId,
        forked_from_id: parentSessionId,
        thread_source: "user",
      }),
      rolloutLine("session_meta", { id: parentSessionId }),
      rolloutLine("turn_context", {
        turn_id: "019fb928-a14b-7cc3-8445-a15cb0653400",
        model: "gpt-5.6-sol",
      }),
      tokenCount(100, 10),
      rolloutLine("turn_context", {
        turn_id: "019fbdea-0b40-7e13-8539-71ce72d0987f",
        model: "gpt-5.6-sol",
      }),
      tokenCount(20, 2),
    ]);

    expect(records).toHaveLength(1);
    expect(records[0]?.sessionId).toBe(childSessionId);
    expect(records[0]?.totals.outputTokens).toBe(2);
  });
});
