// @effect-diagnostics nodeBuiltinImport:off - this maintainer script reads and writes source files before the app runtime exists.
/** Regenerates src/icons/index.ts from the Lucide icons the web app actually imports. */
import * as NodeFS from "node:fs";
import * as NodePath from "node:path";

import { assertKnownIconNames, collectRuntimeIconNames } from "../src/icons/icon-import-parser.ts";

// The generator inspects Lucide's exports before it writes the barrel.
// eslint-disable-next-line no-restricted-imports
import * as lucide from "lucide-react";

const webRoot = NodePath.resolve(import.meta.dirname, "..");
const srcRoot = NodePath.join(webRoot, "src");
const testRoot = NodePath.join(webRoot, "test");
const iconsRoot = NodePath.join(srcRoot, "icons");

function listSourceFiles(dir: string): string[] {
  if (!NodeFS.existsSync(dir)) return [];
  const files: string[] = [];
  for (const entry of NodeFS.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = NodePath.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (fullPath !== iconsRoot) files.push(...listSourceFiles(fullPath));
    } else if (/\.[jt]sx?$/.test(entry.name)) {
      files.push(fullPath);
    }
  }
  return files;
}

const knownNames = new Set(Object.keys(lucide));
const usedNames = new Set<string>();

for (const root of [srcRoot, testRoot]) {
  for (const file of listSourceFiles(root)) {
    const names = collectRuntimeIconNames(NodeFS.readFileSync(file, "utf8"), file);
    assertKnownIconNames(names, knownNames, file);
    for (const name of names) usedNames.add(name);
  }
}

const sortedNames = [...usedNames].sort((left, right) => left.localeCompare(right, "en-US"));
const indexFile = `// Generated by scripts/generate-icon-barrel.ts — do not edit by hand.
// Rerun with: node apps/web/scripts/generate-icon-barrel.ts
/* eslint-disable no-restricted-imports -- this barrel owns direct Lucide imports. */
export {
${sortedNames.map((name) => `  ${name},`).join("\n")}
} from "lucide-react";

export type { LucideIcon, LucideProps } from "lucide-react";
`;
const indexPath = NodePath.join(iconsRoot, "index.ts");

if (process.argv.includes("--check")) {
  const currentIndex = NodeFS.readFileSync(indexPath, "utf8");
  if (currentIndex !== indexFile) {
    throw new Error(
      "src/icons/index.ts is stale. Run `vp run --filter @t3tools/web icons:generate`.",
    );
  }
  console.log(`Verified ${sortedNames.length} generated Lucide exports in src/icons/index.ts.`);
} else {
  NodeFS.mkdirSync(iconsRoot, { recursive: true });
  NodeFS.writeFileSync(indexPath, indexFile);
  console.log(`Generated ${sortedNames.length} Lucide exports in src/icons/index.ts.`);
}
