import * as NodeCrypto from "node:crypto";

const WORKSPACE_NAME_PREFIX = "t3-";
const WORKSPACE_DIGEST_LENGTH = 8;
const WORKSPACE_NAME_PATTERN = new RegExp(
  `^${WORKSPACE_NAME_PREFIX}.+-[0-9a-f]{${WORKSPACE_DIGEST_LENGTH}}$`,
);

export function bookmarkDigest(refName: string): string {
  return NodeCrypto.createHash("sha256")
    .update(refName)
    .digest("hex")
    .slice(0, WORKSPACE_DIGEST_LENGTH);
}

/** Includes a digest so bookmarks such as `a/b` and `a-b` name different workspaces. */
export function workspaceNameForRef(refName: string): string {
  return `${WORKSPACE_NAME_PREFIX}${refName.replaceAll("/", "-")}-${bookmarkDigest(refName)}`;
}

/** True for names generated by {@link workspaceNameForRef}, and false for `default`. */
export function isT3WorkspaceName(name: string): boolean {
  return WORKSPACE_NAME_PATTERN.test(name);
}
