/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as SlackRouteImport } from './routes/slack'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PairRouteImport } from './routes/pair'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EmailRouteImport } from './routes/email'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as WorkspaceChatRouteImport } from './routes/_workspace-chat'
import { Route as WorkspaceChatIndexRouteImport } from './routes/_workspace-chat.index'
import { Route as SettingsSourceControlRouteImport } from './routes/settings.source-control'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsKeybindingsRouteImport } from './routes/settings.keybindings'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsDiagnosticsRouteImport } from './routes/settings.diagnostics'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as SessionTasksResetPasswordRouteImport } from './routes/session-tasks.reset-password'
import { Route as WorkspaceChatDraftDraftIdRouteImport } from './routes/_workspace-chat.draft.$draftId'
import { Route as WorkspaceChatEnvironmentIdThreadIdRouteImport } from './routes/_workspace-chat.$environmentId.$threadId'

const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const SlackRoute = SlackRouteImport.update({
  id: '/slack',
  path: '/slack',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceChatRoute = WorkspaceChatRouteImport.update({
  id: '/_workspace-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceChatIndexRoute = WorkspaceChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceChatRoute,
} as any)
const SettingsSourceControlRoute = SettingsSourceControlRouteImport.update({
  id: '/source-control',
  path: '/source-control',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsKeybindingsRoute = SettingsKeybindingsRouteImport.update({
  id: '/keybindings',
  path: '/keybindings',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDiagnosticsRoute = SettingsDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const SessionTasksResetPasswordRoute =
  SessionTasksResetPasswordRouteImport.update({
    id: '/session-tasks/reset-password',
    path: '/session-tasks/reset-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspaceChatDraftDraftIdRoute =
  WorkspaceChatDraftDraftIdRouteImport.update({
    id: '/draft/$draftId',
    path: '/draft/$draftId',
    getParentRoute: () => WorkspaceChatRoute,
  } as any)
const WorkspaceChatEnvironmentIdThreadIdRoute =
  WorkspaceChatEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => WorkspaceChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceChatIndexRoute
  '/analytics': typeof AnalyticsRoute
  '/chat': typeof ChatRoute
  '/clients': typeof ClientsRoute
  '/email': typeof EmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/issues': typeof IssuesRoute
  '/login': typeof LoginRoute
  '/pair': typeof PairRoute
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/slack': typeof SlackRoute
  '/tracker': typeof TrackerRoute
  '/session-tasks/reset-password': typeof SessionTasksResetPasswordRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/$environmentId/$threadId': typeof WorkspaceChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof WorkspaceChatDraftDraftIdRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof AnalyticsRoute
  '/chat': typeof ChatRoute
  '/clients': typeof ClientsRoute
  '/email': typeof EmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/issues': typeof IssuesRoute
  '/login': typeof LoginRoute
  '/pair': typeof PairRoute
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/slack': typeof SlackRoute
  '/tracker': typeof TrackerRoute
  '/session-tasks/reset-password': typeof SessionTasksResetPasswordRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/': typeof WorkspaceChatIndexRoute
  '/$environmentId/$threadId': typeof WorkspaceChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof WorkspaceChatDraftDraftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_workspace-chat': typeof WorkspaceChatRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/chat': typeof ChatRoute
  '/clients': typeof ClientsRoute
  '/email': typeof EmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/issues': typeof IssuesRoute
  '/login': typeof LoginRoute
  '/pair': typeof PairRoute
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/slack': typeof SlackRoute
  '/tracker': typeof TrackerRoute
  '/session-tasks/reset-password': typeof SessionTasksResetPasswordRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/_workspace-chat/': typeof WorkspaceChatIndexRoute
  '/_workspace-chat/$environmentId/$threadId': typeof WorkspaceChatEnvironmentIdThreadIdRoute
  '/_workspace-chat/draft/$draftId': typeof WorkspaceChatDraftDraftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/chat'
    | '/clients'
    | '/email'
    | '/forgot-password'
    | '/issues'
    | '/login'
    | '/pair'
    | '/projects'
    | '/register'
    | '/settings'
    | '/slack'
    | '/tracker'
    | '/session-tasks/reset-password'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/keybindings'
    | '/settings/profile'
    | '/settings/providers'
    | '/settings/source-control'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/chat'
    | '/clients'
    | '/email'
    | '/forgot-password'
    | '/issues'
    | '/login'
    | '/pair'
    | '/projects'
    | '/register'
    | '/settings'
    | '/slack'
    | '/tracker'
    | '/session-tasks/reset-password'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/keybindings'
    | '/settings/profile'
    | '/settings/providers'
    | '/settings/source-control'
    | '/'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
  id:
    | '__root__'
    | '/_workspace-chat'
    | '/analytics'
    | '/chat'
    | '/clients'
    | '/email'
    | '/forgot-password'
    | '/issues'
    | '/login'
    | '/pair'
    | '/projects'
    | '/register'
    | '/settings'
    | '/slack'
    | '/tracker'
    | '/session-tasks/reset-password'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/keybindings'
    | '/settings/profile'
    | '/settings/providers'
    | '/settings/source-control'
    | '/_workspace-chat/'
    | '/_workspace-chat/$environmentId/$threadId'
    | '/_workspace-chat/draft/$draftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkspaceChatRoute: typeof WorkspaceChatRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  ChatRoute: typeof ChatRoute
  ClientsRoute: typeof ClientsRoute
  EmailRoute: typeof EmailRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IssuesRoute: typeof IssuesRoute
  LoginRoute: typeof LoginRoute
  PairRoute: typeof PairRoute
  ProjectsRoute: typeof ProjectsRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SlackRoute: typeof SlackRoute
  TrackerRoute: typeof TrackerRoute
  SessionTasksResetPasswordRoute: typeof SessionTasksResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slack': {
      id: '/slack'
      path: '/slack'
      fullPath: '/slack'
      preLoaderRoute: typeof SlackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace-chat': {
      id: '/_workspace-chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace-chat/': {
      id: '/_workspace-chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceChatIndexRouteImport
      parentRoute: typeof WorkspaceChatRoute
    }
    '/settings/source-control': {
      id: '/settings/source-control'
      path: '/source-control'
      fullPath: '/settings/source-control'
      preLoaderRoute: typeof SettingsSourceControlRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/keybindings': {
      id: '/settings/keybindings'
      path: '/keybindings'
      fullPath: '/settings/keybindings'
      preLoaderRoute: typeof SettingsKeybindingsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/diagnostics': {
      id: '/settings/diagnostics'
      path: '/diagnostics'
      fullPath: '/settings/diagnostics'
      preLoaderRoute: typeof SettingsDiagnosticsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/session-tasks/reset-password': {
      id: '/session-tasks/reset-password'
      path: '/session-tasks/reset-password'
      fullPath: '/session-tasks/reset-password'
      preLoaderRoute: typeof SessionTasksResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace-chat/draft/$draftId': {
      id: '/_workspace-chat/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/draft/$draftId'
      preLoaderRoute: typeof WorkspaceChatDraftDraftIdRouteImport
      parentRoute: typeof WorkspaceChatRoute
    }
    '/_workspace-chat/$environmentId/$threadId': {
      id: '/_workspace-chat/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/$environmentId/$threadId'
      preLoaderRoute: typeof WorkspaceChatEnvironmentIdThreadIdRouteImport
      parentRoute: typeof WorkspaceChatRoute
    }
  }
}

interface WorkspaceChatRouteChildren {
  WorkspaceChatIndexRoute: typeof WorkspaceChatIndexRoute
  WorkspaceChatEnvironmentIdThreadIdRoute: typeof WorkspaceChatEnvironmentIdThreadIdRoute
  WorkspaceChatDraftDraftIdRoute: typeof WorkspaceChatDraftDraftIdRoute
}

const WorkspaceChatRouteChildren: WorkspaceChatRouteChildren = {
  WorkspaceChatIndexRoute: WorkspaceChatIndexRoute,
  WorkspaceChatEnvironmentIdThreadIdRoute:
    WorkspaceChatEnvironmentIdThreadIdRoute,
  WorkspaceChatDraftDraftIdRoute: WorkspaceChatDraftDraftIdRoute,
}

const WorkspaceChatRouteWithChildren = WorkspaceChatRoute._addFileChildren(
  WorkspaceChatRouteChildren,
)

interface SettingsRouteChildren {
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsDiagnosticsRoute: typeof SettingsDiagnosticsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsKeybindingsRoute: typeof SettingsKeybindingsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsSourceControlRoute: typeof SettingsSourceControlRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsDiagnosticsRoute: SettingsDiagnosticsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsKeybindingsRoute: SettingsKeybindingsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsSourceControlRoute: SettingsSourceControlRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WorkspaceChatRoute: WorkspaceChatRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  ChatRoute: ChatRoute,
  ClientsRoute: ClientsRoute,
  EmailRoute: EmailRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IssuesRoute: IssuesRoute,
  LoginRoute: LoginRoute,
  PairRoute: PairRoute,
  ProjectsRoute: ProjectsRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SlackRoute: SlackRoute,
  TrackerRoute: TrackerRoute,
  SessionTasksResetPasswordRoute: SessionTasksResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
