/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as ChatSettingsRouteImport } from './routes/_chat.settings'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'
import { Route as ChatSettingsGeneralRouteImport } from './routes/_chat.settings.general'
import { Route as ChatSettingsArchivedRouteImport } from './routes/_chat.settings.archived'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSettingsGeneralRoute = ChatSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => ChatSettingsRoute,
} as any)
const ChatSettingsArchivedRoute = ChatSettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => ChatSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/settings': typeof ChatSettingsRouteWithChildren
  '/settings/archived': typeof ChatSettingsArchivedRoute
  '/settings/general': typeof ChatSettingsGeneralRoute
}
export interface FileRoutesByTo {
  '/$threadId': typeof ChatThreadIdRoute
  '/settings': typeof ChatSettingsRouteWithChildren
  '/': typeof ChatIndexRoute
  '/settings/archived': typeof ChatSettingsArchivedRoute
  '/settings/general': typeof ChatSettingsGeneralRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/_chat/settings': typeof ChatSettingsRouteWithChildren
  '/_chat/': typeof ChatIndexRoute
  '/_chat/settings/archived': typeof ChatSettingsArchivedRoute
  '/_chat/settings/general': typeof ChatSettingsGeneralRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$threadId'
    | '/settings'
    | '/settings/archived'
    | '/settings/general'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$threadId'
    | '/settings'
    | '/'
    | '/settings/archived'
    | '/settings/general'
  id:
    | '__root__'
    | '/_chat'
    | '/_chat/$threadId'
    | '/_chat/settings'
    | '/_chat/'
    | '/_chat/settings/archived'
    | '/_chat/settings/general'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/settings': {
      id: '/_chat/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ChatSettingsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/settings/general': {
      id: '/_chat/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof ChatSettingsGeneralRouteImport
      parentRoute: typeof ChatSettingsRoute
    }
    '/_chat/settings/archived': {
      id: '/_chat/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof ChatSettingsArchivedRouteImport
      parentRoute: typeof ChatSettingsRoute
    }
  }
}

interface ChatSettingsRouteChildren {
  ChatSettingsArchivedRoute: typeof ChatSettingsArchivedRoute
  ChatSettingsGeneralRoute: typeof ChatSettingsGeneralRoute
}

const ChatSettingsRouteChildren: ChatSettingsRouteChildren = {
  ChatSettingsArchivedRoute: ChatSettingsArchivedRoute,
  ChatSettingsGeneralRoute: ChatSettingsGeneralRoute,
}

const ChatSettingsRouteWithChildren = ChatSettingsRoute._addFileChildren(
  ChatSettingsRouteChildren,
)

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatSettingsRoute: typeof ChatSettingsRouteWithChildren
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatSettingsRoute: ChatSettingsRouteWithChildren,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
