/**
 * CSS generation for theme palettes.
 *
 * This module is imported by both the generation script
 * (`apps/web/scripts/generate-theme-css.ts`) and the test suite so the
 * generated `themePalettes.css` is guaranteed to match the canonical data in
 * `themePalettes.ts`.
 */
import { DEFAULT_THEME_PALETTE, THEME_PALETTES, type ThemePaletteColors } from "./themePalettes.ts";

function emitPaletteBlock(selector: string, colors: ThemePaletteColors): string {
  return [
    `${selector} {`,
    `  --palette-primary: ${colors.primary};`,
    `  --palette-on-primary: ${colors.onPrimary};`,
    `  --palette-secondary: ${colors.secondary};`,
    `  --palette-on-secondary: ${colors.onSecondary};`,
    `  --palette-tertiary: ${colors.tertiary};`,
    `  --palette-on-tertiary: ${colors.onTertiary};`,
    `  --palette-error: ${colors.error};`,
    `  --palette-surface: ${colors.surface};`,
    `  --palette-on-surface: ${colors.onSurface};`,
    `  --palette-surface-variant: ${colors.surfaceVariant};`,
    `  --palette-on-surface-variant: ${colors.onSurfaceVariant};`,
    `  --palette-outline: ${colors.outline};`,
    `}`,
  ].join("\n");
}

export function generateThemePalettesCss(): string {
  const header =
    "/* Generated by apps/web/scripts/generate-theme-css.ts. Do not edit by hand. */\n\n" +
    "/* Palette values are adapted from Noctalia Shell's built-in palettes. */";
  const blocks: string[] = [];

  for (const palette of THEME_PALETTES) {
    const selector =
      palette.id === DEFAULT_THEME_PALETTE
        ? `:root,\n:root[data-theme-palette="${palette.id}"]`
        : `:root[data-theme-palette="${palette.id}"]`;
    blocks.push(emitPaletteBlock(selector, palette.light));
  }

  for (const palette of THEME_PALETTES) {
    const selector =
      palette.id === DEFAULT_THEME_PALETTE
        ? `:root.dark,\n:root.dark[data-theme-palette="${palette.id}"]`
        : `:root.dark[data-theme-palette="${palette.id}"]`;
    blocks.push(emitPaletteBlock(selector, palette.dark));
  }

  return `${header}\n\n${blocks.join("\n\n")}\n`;
}
