// Regenerates qml/T3/Bricks/js/lucide.js: the stroke paths of the lucide
// icons the bricks draw, flattened to one SVG path per icon on a 24-unit grid
// so ShellIcon needs a single PathSvg. Add a name to ICONS and run
// `node apps/desktop-qt/scripts/gen-icons.mjs` from the repo root; the icon
// data comes from the lucide-react package the web app depends on.
import { createRequire } from "node:module";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ICONS = [
  "arrow-up",
  "bot",
  "chart-no-axes-column",
  "check",
  "chevron-down",
  "chevron-right",
  "chevron-up",
  "circle-dashed",
  "cloud",
  "cloud-upload",
  "copy",
  "external-link",
  "file-diff",
  "files",
  "folder",
  "folder-git",
  "folder-git-2",
  "folder-plus",
  "git-branch",
  "git-commit-horizontal",
  "git-merge",
  "git-pull-request",
  "image",
  "lock",
  "lock-open",
  "minus",
  "monitor",
  "panel-left",
  "panel-left-close",
  "panel-right",
  "panel-right-close",
  "paperclip",
  "pencil-ruler",
  "pen-line",
  "play",
  "plus",
  "search",
  "settings",
  "sparkles",
  "square",
  "square-pen",
  "terminal",
  "x",
];

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..", "..");
const require = createRequire(join(repoRoot, "apps/web/package.json"));
const iconsDir = dirname(require.resolve("lucide-react/dist/esm/icons/x.js"));
const output = join(here, "..", "qml/T3/Bricks/js/lucide.js");

const num = (value) => Number(value);
const arc = (cx, cy, rx, ry) =>
  `M${cx - rx} ${cy}a${rx} ${ry} 0 1 0 ${2 * rx} 0a${rx} ${ry} 0 1 0 ${-2 * rx} 0`;
const points = (raw, close) => {
  const p = raw.trim().split(/[\s,]+/);
  let d = `M${p[0]} ${p[1]}`;
  for (let i = 2; i < p.length; i += 2) d += `L${p[i]} ${p[i + 1]}`;
  return close ? d + "Z" : d;
};

const toPath = ([tag, a]) => {
  switch (tag) {
    // Each <path> starts at the origin, so a leading relative move is an
    // absolute one; the implicit pairs after it stay relative lines.
    case "path":
      return a.d
        .trim()
        .replace(
          /^m\s*(-?[\d.]+)[\s,]*(-?[\d.]+)\s*(.*)$/,
          (_, x, y, rest) => `M${x} ${y}${/^[-\d.]/.test(rest) ? "l" : ""}${rest}`,
        );
    case "line":
      return `M${a.x1} ${a.y1}L${a.x2} ${a.y2}`;
    case "polyline":
      return points(a.points, false);
    case "polygon":
      return points(a.points, true);
    case "circle":
      return arc(num(a.cx), num(a.cy), num(a.r), num(a.r));
    case "ellipse":
      return arc(num(a.cx), num(a.cy), num(a.rx), num(a.ry));
    case "rect": {
      const x = num(a.x ?? 0);
      const y = num(a.y ?? 0);
      const w = num(a.width);
      const h = num(a.height);
      const r = num(a.rx ?? a.ry ?? 0);
      if (!r) return `M${x} ${y}h${w}v${h}h${-w}Z`;
      return (
        `M${x + r} ${y}h${w - 2 * r}a${r} ${r} 0 0 1 ${r} ${r}v${h - 2 * r}` +
        `a${r} ${r} 0 0 1 ${-r} ${r}h${-(w - 2 * r)}a${r} ${r} 0 0 1 ${-r} ${-r}` +
        `v${-(h - 2 * r)}a${r} ${r} 0 0 1 ${r} ${-r}Z`
      );
    }
    default:
      throw new Error(`unhandled svg element ${tag}`);
  }
};

const paths = {};
for (const name of ICONS) {
  const source = readFileSync(join(iconsDir, `${name}.js`), "utf8");
  const match = source.match(/const __iconNode = (\[[\s\S]*?\]);\nconst /);
  if (!match) throw new Error(`no icon node in ${name}`);
  const nodes = new Function(`return ${match[1]}`)();
  paths[name] = nodes.map(toPath).join("");
}

const body = Object.entries(paths)
  .map(([name, d]) => `    "${name}": "${d}"`)
  .join(",\n");

writeFileSync(
  output,
  `.pragma library

// Stroke path data for the lucide icons the bricks draw (ISC, lucide.dev),
// flattened to one SVG path per icon on a 24-unit grid. Generated by
// apps/desktop-qt/scripts/gen-icons.mjs; edit the list there, not this file.
var paths = {
${body}
};

function path(name) {
    return paths[name] ?? "";
}
`,
);
console.log(`${ICONS.length} icons -> ${output}`);
