/**
 * User-configurable MCP server contracts.
 *
 * These describe MCP servers a user registers once, in one settings panel,
 * so they can be merged into whichever agent CLI (Claude/Codex/Grok/Cursor/
 * OpenCode) is driving a given thread — instead of configuring MCP
 * separately inside each vendor's own settings.
 *
 * @module mcpServers
 */
import * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import { TrimmedNonEmptyString } from "./baseSchemas.ts";

/**
 * Routing key for a configured MCP server, used as the key of
 * `ServerSettings.mcpServers`. Not a slug — generated by the client (e.g. a
 * UUID) rather than typed by the user, so it only needs to be a non-empty
 * string.
 */
export const McpServerId = TrimmedNonEmptyString.pipe(Schema.brand("McpServerId"));
export type McpServerId = typeof McpServerId.Type;

const MCP_SERVER_HEADER_NAME_MAX_CHARS = 256;
export const McpServerHeaderName = TrimmedNonEmptyString.check(
  Schema.isMaxLength(MCP_SERVER_HEADER_NAME_MAX_CHARS),
);
export type McpServerHeaderName = typeof McpServerHeaderName.Type;

/**
 * An HTTP/SSE header sent to a remote MCP server. Mirrors
 * `ProviderInstanceEnvironmentVariable` exactly so the same
 * redact-and-store-in-`ServerSecretStore` handling can be reused verbatim.
 */
export const McpServerHeader = Schema.Struct({
  name: McpServerHeaderName,
  value: Schema.String.pipe(Schema.withDecodingDefault(Effect.succeed(""))),
  sensitive: Schema.Boolean.pipe(Schema.withDecodingDefault(Effect.succeed(false))),
  valueRedacted: Schema.optionalKey(Schema.Boolean),
});
export type McpServerHeader = typeof McpServerHeader.Type;
export const McpServerHeaders = Schema.Array(McpServerHeader);
export type McpServerHeaders = typeof McpServerHeaders.Type;

const MCP_SERVER_ENV_VAR_NAME_MAX_CHARS = 128;
const MCP_SERVER_ENV_VAR_NAME_PATTERN = /^[a-zA-Z_][a-zA-Z0-9_]*$/;
export const McpServerEnvVarName = TrimmedNonEmptyString.check(
  Schema.isMaxLength(MCP_SERVER_ENV_VAR_NAME_MAX_CHARS),
  Schema.isPattern(MCP_SERVER_ENV_VAR_NAME_PATTERN),
);
export type McpServerEnvVarName = typeof McpServerEnvVarName.Type;

/**
 * An environment variable passed to a locally-spawned (stdio) MCP server.
 * Mirrors `ProviderInstanceEnvironmentVariable`.
 */
export const McpServerEnvVar = Schema.Struct({
  name: McpServerEnvVarName,
  value: Schema.String.pipe(Schema.withDecodingDefault(Effect.succeed(""))),
  sensitive: Schema.Boolean.pipe(Schema.withDecodingDefault(Effect.succeed(false))),
  valueRedacted: Schema.optionalKey(Schema.Boolean),
});
export type McpServerEnvVar = typeof McpServerEnvVar.Type;
export const McpServerEnvVars = Schema.Array(McpServerEnvVar);
export type McpServerEnvVars = typeof McpServerEnvVars.Type;

export const McpServerStdioTransport = Schema.Struct({
  type: Schema.Literal("stdio"),
  command: TrimmedNonEmptyString,
  args: Schema.Array(Schema.String).pipe(Schema.withDecodingDefault(Effect.succeed([]))),
  cwd: Schema.optional(TrimmedNonEmptyString),
  env: Schema.optionalKey(McpServerEnvVars),
});
export type McpServerStdioTransport = typeof McpServerStdioTransport.Type;

export const McpServerRemoteTransportKind = Schema.Literals(["http", "sse"]);
export type McpServerRemoteTransportKind = typeof McpServerRemoteTransportKind.Type;

export const McpServerRemoteTransport = Schema.Struct({
  type: McpServerRemoteTransportKind,
  url: TrimmedNonEmptyString,
  headers: Schema.optionalKey(McpServerHeaders),
});
export type McpServerRemoteTransport = typeof McpServerRemoteTransport.Type;

export const McpServerTransport = Schema.Union([McpServerStdioTransport, McpServerRemoteTransport]);
export type McpServerTransport = typeof McpServerTransport.Type;

/**
 * Envelope shape for one MCP server in `ServerSettings.mcpServers`. `name` is
 * a user-facing display name (distinct from the map key `McpServerId`).
 * Disabled servers are kept in settings but excluded when resolving the set
 * of MCP servers to merge into a session.
 */
export const McpServerConfig = Schema.Struct({
  name: TrimmedNonEmptyString,
  enabled: Schema.Boolean.pipe(Schema.withDecodingDefault(Effect.succeed(true))),
  transport: McpServerTransport,
});
export type McpServerConfig = typeof McpServerConfig.Type;

/** Map shape for `ServerSettings.mcpServers`. */
export const McpServerConfigMap = Schema.Record(McpServerId, McpServerConfig);
export type McpServerConfigMap = typeof McpServerConfigMap.Type;

// ── RPC payloads ────────────────────────────────────────────────

export const McpServerUpsertInput = Schema.Struct({
  id: Schema.optional(McpServerId),
  config: McpServerConfig,
});
export type McpServerUpsertInput = typeof McpServerUpsertInput.Type;

export const McpServerUpsertResult = Schema.Struct({
  id: McpServerId,
  config: McpServerConfig,
});
export type McpServerUpsertResult = typeof McpServerUpsertResult.Type;

export const McpServerRemoveInput = Schema.Struct({
  id: McpServerId,
});
export type McpServerRemoveInput = typeof McpServerRemoveInput.Type;

export const McpServerListEntry = Schema.Struct({
  id: McpServerId,
  config: McpServerConfig,
});
export type McpServerListEntry = typeof McpServerListEntry.Type;

export const McpServersListResult = Schema.Struct({
  servers: Schema.Array(McpServerListEntry),
});
export type McpServersListResult = typeof McpServersListResult.Type;

/**
 * Either `id` (test an already-saved server) or `config` (test a draft
 * before saving it) must be provided; the server resolves whichever is set.
 */
export const McpServerTestConnectionInput = Schema.Struct({
  id: Schema.optional(McpServerId),
  config: Schema.optional(McpServerConfig),
});
export type McpServerTestConnectionInput = typeof McpServerTestConnectionInput.Type;

export const McpServerTestConnectionStatus = Schema.Literals(["ok", "error"]);
export type McpServerTestConnectionStatus = typeof McpServerTestConnectionStatus.Type;

export const McpServerTestConnectionResult = Schema.Struct({
  status: McpServerTestConnectionStatus,
  toolNames: Schema.Array(Schema.String),
  detail: Schema.optional(Schema.String),
});
export type McpServerTestConnectionResult = typeof McpServerTestConnectionResult.Type;

export class McpServerRegistryError extends Schema.TaggedErrorClass<McpServerRegistryError>()(
  "McpServerRegistryError",
  {
    operation: Schema.String,
    id: Schema.optional(Schema.String),
    detail: Schema.String,
    cause: Schema.optional(Schema.Defect()),
  },
) {
  override get message(): string {
    return `MCP server registry operation ${this.operation} failed: ${this.detail}`;
  }
}
