import {
  ProjectCreatedPayload as ContractsProjectCreatedPayloadSchema,
  ProjectMetaUpdatedPayload as ContractsProjectMetaUpdatedPayloadSchema,
  ProjectDeletedPayload as ContractsProjectDeletedPayloadSchema,
  ThreadCreatedPayload as ContractsThreadCreatedPayloadSchema,
  ThreadForkedPayload as ContractsThreadForkedPayloadSchema,
  ThreadArchivedPayload as ContractsThreadArchivedPayloadSchema,
  ThreadMetaUpdatedPayload as ContractsThreadMetaUpdatedPayloadSchema,
  ThreadRuntimeModeSetPayload as ContractsThreadRuntimeModeSetPayloadSchema,
  ThreadInteractionModeSetPayload as ContractsThreadInteractionModeSetPayloadSchema,
  ThreadDeletedPayload as ContractsThreadDeletedPayloadSchema,
  ThreadUnarchivedPayload as ContractsThreadUnarchivedPayloadSchema,
  ThreadMessageSentPayload as ContractsThreadMessageSentPayloadSchema,
  ThreadTurnEnqueuedPayload as ContractsThreadTurnEnqueuedPayloadSchema,
  ThreadTurnQueueItemRemovedPayload as ContractsThreadTurnQueueItemRemovedPayloadSchema,
  ThreadTurnQueuePausedPayload as ContractsThreadTurnQueuePausedPayloadSchema,
  ThreadTurnQueueResumedPayload as ContractsThreadTurnQueueResumedPayloadSchema,
  ThreadProposedPlanUpsertedPayload as ContractsThreadProposedPlanUpsertedPayloadSchema,
  ThreadSessionSetPayload as ContractsThreadSessionSetPayloadSchema,
  ThreadTurnDiffCompletedPayload as ContractsThreadTurnDiffCompletedPayloadSchema,
  ThreadTurnSettledPayload as ContractsThreadTurnSettledPayloadSchema,
  ThreadRevertedPayload as ContractsThreadRevertedPayloadSchema,
  ThreadActivityAppendedPayload as ContractsThreadActivityAppendedPayloadSchema,
  ThreadTurnStartRequestedPayload as ContractsThreadTurnStartRequestedPayloadSchema,
  ThreadTurnInterruptRequestedPayload as ContractsThreadTurnInterruptRequestedPayloadSchema,
  ThreadApprovalResponseRequestedPayload as ContractsThreadApprovalResponseRequestedPayloadSchema,
  ThreadCheckpointRevertRequestedPayload as ContractsThreadCheckpointRevertRequestedPayloadSchema,
  ThreadSessionStopRequestedPayload as ContractsThreadSessionStopRequestedPayloadSchema,
} from "@forma/contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const ProjectCreatedPayload = ContractsProjectCreatedPayloadSchema;
export const ProjectMetaUpdatedPayload = ContractsProjectMetaUpdatedPayloadSchema;
export const ProjectDeletedPayload = ContractsProjectDeletedPayloadSchema;

export const ThreadCreatedPayload = ContractsThreadCreatedPayloadSchema;
export const ThreadForkedPayload = ContractsThreadForkedPayloadSchema;
export const ThreadArchivedPayload = ContractsThreadArchivedPayloadSchema;
export const ThreadMetaUpdatedPayload = ContractsThreadMetaUpdatedPayloadSchema;
export const ThreadRuntimeModeSetPayload = ContractsThreadRuntimeModeSetPayloadSchema;
export const ThreadInteractionModeSetPayload = ContractsThreadInteractionModeSetPayloadSchema;
export const ThreadDeletedPayload = ContractsThreadDeletedPayloadSchema;
export const ThreadUnarchivedPayload = ContractsThreadUnarchivedPayloadSchema;

export const MessageSentPayloadSchema = ContractsThreadMessageSentPayloadSchema;
export const ThreadTurnEnqueuedPayload = ContractsThreadTurnEnqueuedPayloadSchema;
export const ThreadTurnQueueItemRemovedPayload = ContractsThreadTurnQueueItemRemovedPayloadSchema;
export const ThreadTurnQueuePausedPayload = ContractsThreadTurnQueuePausedPayloadSchema;
export const ThreadTurnQueueResumedPayload = ContractsThreadTurnQueueResumedPayloadSchema;
export const ThreadProposedPlanUpsertedPayload = ContractsThreadProposedPlanUpsertedPayloadSchema;
export const ThreadSessionSetPayload = ContractsThreadSessionSetPayloadSchema;
export const ThreadTurnDiffCompletedPayload = ContractsThreadTurnDiffCompletedPayloadSchema;
export const ThreadTurnSettledPayload = ContractsThreadTurnSettledPayloadSchema;
export const ThreadRevertedPayload = ContractsThreadRevertedPayloadSchema;
export const ThreadActivityAppendedPayload = ContractsThreadActivityAppendedPayloadSchema;

export const ThreadTurnStartRequestedPayload = ContractsThreadTurnStartRequestedPayloadSchema;
export const ThreadTurnInterruptRequestedPayload =
  ContractsThreadTurnInterruptRequestedPayloadSchema;
export const ThreadApprovalResponseRequestedPayload =
  ContractsThreadApprovalResponseRequestedPayloadSchema;
export const ThreadCheckpointRevertRequestedPayload =
  ContractsThreadCheckpointRevertRequestedPayloadSchema;
export const ThreadSessionStopRequestedPayload = ContractsThreadSessionStopRequestedPayloadSchema;
