export const PLUGIN_HOST_IMPORT_MAP_MARKER = "data-t3-plugin-host-importmap";
export const PLUGIN_HOST_BOOTSTRAP_MARKER = "data-t3-plugin-host-bootstrap";
export const PLUGIN_WEB_BUNDLE_CACHE_CONTROL = "public, max-age=31536000, immutable";
export const PLUGIN_WEB_SHIM_CACHE_CONTROL = "public, max-age=60";

/**
 * The runtime import map handed to plugin web bundles. It maps ONLY the bare
 * module specifiers below — NOT effect subpaths.
 *
 * Plugin web bundles must import effect from the barrel
 * (`import { Effect, Schema } from "effect"`), never a subpath
 * (`import * as Effect from "effect/Effect"` does not resolve in the browser).
 * This is a deliberate v1 constraint: web plugins resolve shared modules
 * through the native browser import map, which enumerates bare specifiers
 * only. (Server plugins differ — a Node resolve hook handles subpaths there.)
 * If per-subpath support is ever needed, add `effect/<Sub>` entries here AND
 * generate a shim per subpath that forwards that subpath's own members.
 */
export const pluginHostImportMap = {
  imports: {
    react: "/plugin-host/react.js",
    "react-dom": "/plugin-host/react-dom.js",
    "react-dom/client": "/plugin-host/react-dom/client.js",
    "react/jsx-runtime": "/plugin-host/react/jsx-runtime.js",
    "react/jsx-dev-runtime": "/plugin-host/react/jsx-dev-runtime.js",
    "@effect/atom-react": "/plugin-host/@effect/atom-react.js",
    effect: "/plugin-host/effect.js",
    "@t3tools/plugin-sdk-web": "/plugin-host/@t3tools/plugin-sdk-web.js",
  },
} as const;

export type PluginHostModuleSpecifier = keyof typeof pluginHostImportMap.imports;

export const pluginHostModuleSpecifiers = Object.keys(
  pluginHostImportMap.imports,
) as ReadonlyArray<PluginHostModuleSpecifier>;

const reactExports = [
  "Activity",
  "Children",
  "Component",
  "Fragment",
  "Profiler",
  "PureComponent",
  "StrictMode",
  "Suspense",
  "__CLIENT_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE",
  "__COMPILER_RUNTIME",
  "act",
  "cache",
  "cacheSignal",
  "captureOwnerStack",
  "cloneElement",
  "createContext",
  "createElement",
  "createRef",
  "forwardRef",
  "isValidElement",
  "lazy",
  "memo",
  "startTransition",
  "unstable_useCacheRefresh",
  "use",
  "useActionState",
  "useCallback",
  "useContext",
  "useDebugValue",
  "useDeferredValue",
  "useEffect",
  "useEffectEvent",
  "useId",
  "useImperativeHandle",
  "useInsertionEffect",
  "useLayoutEffect",
  "useMemo",
  "useOptimistic",
  "useReducer",
  "useRef",
  "useState",
  "useSyncExternalStore",
  "useTransition",
  "version",
] as const;

const reactDomExports = [
  "__DOM_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE",
  "createPortal",
  "flushSync",
  "preconnect",
  "prefetchDNS",
  "preinit",
  "preinitModule",
  "preload",
  "preloadModule",
  "requestFormReset",
  "unstable_batchedUpdates",
  "useFormState",
  "useFormStatus",
  "version",
] as const;

const reactDomClientExports = ["createRoot", "hydrateRoot", "version"] as const;
const jsxRuntimeExports = ["Fragment", "jsx", "jsxs"] as const;
const jsxDevRuntimeExports = ["Fragment", "jsxDEV"] as const;

const atomReactExports = [
  "HydrationBoundary",
  "RegistryContext",
  "RegistryProvider",
  "TypeId",
  "make",
  "scheduleTask",
  "useAtom",
  "useAtomInitialValues",
  "useAtomMount",
  "useAtomRef",
  "useAtomRefProp",
  "useAtomRefPropValue",
  "useAtomRefresh",
  "useAtomSet",
  "useAtomSubscribe",
  "useAtomSuspense",
  "useAtomValue",
] as const;

const effectExports = [
  "Array",
  "BigDecimal",
  "BigInt",
  "Boolean",
  "Brand",
  "Cache",
  "Cause",
  "Channel",
  "ChannelSchema",
  "Chunk",
  "Clock",
  "Combiner",
  "Config",
  "ConfigProvider",
  "Console",
  "Context",
  "Cron",
  "Crypto",
  "Data",
  "DateTime",
  "Deferred",
  "Differ",
  "Duration",
  "Effect",
  "Effectable",
  "Encoding",
  "Equal",
  "Equivalence",
  "ErrorReporter",
  "ExecutionPlan",
  "Exit",
  "Fiber",
  "FiberHandle",
  "FiberMap",
  "FiberSet",
  "FileSystem",
  "Filter",
  "Formatter",
  "Function",
  "Graph",
  "HKT",
  "Hash",
  "HashMap",
  "HashRing",
  "HashSet",
  "Inspectable",
  "Iterable",
  "JsonPatch",
  "JsonPointer",
  "JsonSchema",
  "Latch",
  "Layer",
  "LayerMap",
  "LogLevel",
  "Logger",
  "ManagedRuntime",
  "Match",
  "Metric",
  "MutableHashMap",
  "MutableHashSet",
  "MutableList",
  "MutableRef",
  "Newtype",
  "NonEmptyIterable",
  "Number",
  "Optic",
  "Option",
  "Order",
  "Ordering",
  "PartitionedSemaphore",
  "Path",
  "Pipeable",
  "PlatformError",
  "Pool",
  "Predicate",
  "PrimaryKey",
  "PubSub",
  "Pull",
  "Queue",
  "Random",
  "RcMap",
  "RcRef",
  "Record",
  "Redactable",
  "Redacted",
  "Reducer",
  "Ref",
  "References",
  "RegExp",
  "Request",
  "RequestResolver",
  "Resource",
  "Result",
  "Runtime",
  "Schedule",
  "Scheduler",
  "Schema",
  "SchemaAST",
  "SchemaGetter",
  "SchemaIssue",
  "SchemaParser",
  "SchemaRepresentation",
  "SchemaTransformation",
  "SchemaUtils",
  "Scope",
  "ScopedCache",
  "ScopedRef",
  "Semaphore",
  "Sink",
  "Stdio",
  "Stream",
  "String",
  "Struct",
  "SubscriptionRef",
  "Symbol",
  "SynchronizedRef",
  "Take",
  "Terminal",
  "Tracer",
  "Trie",
  "Tuple",
  "TxChunk",
  "TxDeferred",
  "TxHashMap",
  "TxHashSet",
  "TxPriorityQueue",
  "TxPubSub",
  "TxQueue",
  "TxReentrantLock",
  "TxRef",
  "TxSemaphore",
  "TxSubscriptionRef",
  "Types",
  "UndefinedOr",
  "Unify",
  "Utils",
  "absurd",
  "cast",
  "flow",
  "hole",
  "identity",
  "pipe",
] as const;

const pluginSdkWebExports = [
  "Alert",
  "AlertAction",
  "AlertDescription",
  "AlertDialog",
  "AlertDialogBackdrop",
  "AlertDialogClose",
  "AlertDialogContent",
  "AlertDialogCreateHandle",
  "AlertDialogDescription",
  "AlertDialogFooter",
  "AlertDialogHeader",
  "AlertDialogOverlay",
  "AlertDialogPopup",
  "AlertDialogPortal",
  "AlertDialogTitle",
  "AlertDialogTrigger",
  "AlertDialogViewport",
  "AlertTitle",
  "AnchoredToastProvider",
  "Badge",
  "Button",
  "Card",
  "CardAction",
  "CardContent",
  "CardDescription",
  "CardFooter",
  "CardFrame",
  "CardFrameDescription",
  "CardFrameFooter",
  "CardFrameHeader",
  "CardFrameTitle",
  "CardHeader",
  "CardPanel",
  "CardTitle",
  "ChatMarkdown",
  "Checkbox",
  "Command",
  "CommandCollection",
  "CommandDialog",
  "CommandDialogPopup",
  "CommandDialogTrigger",
  "CommandEmpty",
  "CommandFooter",
  "CommandGroup",
  "CommandGroupLabel",
  "CommandInput",
  "CommandItem",
  "CommandList",
  "CommandPanel",
  "CommandSeparator",
  "CommandShortcut",
  "Dialog",
  "DialogBackdrop",
  "DialogClose",
  "DialogContent",
  "DialogCreateHandle",
  "DialogDescription",
  "DialogFooter",
  "DialogHeader",
  "DialogOverlay",
  "DialogPanel",
  "DialogPopup",
  "DialogPortal",
  "DialogTitle",
  "DialogTrigger",
  "DialogViewport",
  "DropdownMenu",
  "DropdownMenuCheckboxItem",
  "DropdownMenuContent",
  "DropdownMenuCreateHandle",
  "DropdownMenuGroup",
  "DropdownMenuItem",
  "DropdownMenuLabel",
  "DropdownMenuPortal",
  "DropdownMenuRadioGroup",
  "DropdownMenuRadioItem",
  "DropdownMenuSeparator",
  "DropdownMenuShortcut",
  "DropdownMenuSub",
  "DropdownMenuSubContent",
  "DropdownMenuSubTrigger",
  "DropdownMenuTrigger",
  "Empty",
  "EmptyContent",
  "EmptyDescription",
  "EmptyHeader",
  "EmptyMedia",
  "EmptyTitle",
  "Field",
  "FieldControl",
  "FieldDescription",
  "FieldError",
  "FieldItem",
  "FieldLabel",
  "FieldValidity",
  "HydrationBoundary",
  "Input",
  "Label",
  "Menu",
  "MenuCheckboxItem",
  "MenuCreateHandle",
  "MenuGroup",
  "MenuGroupLabel",
  "MenuItem",
  "MenuPortal",
  "MenuPopup",
  "MenuRadioGroup",
  "MenuRadioItem",
  "MenuSeparator",
  "MenuShortcut",
  "MenuSub",
  "MenuSubPopup",
  "MenuSubTrigger",
  "MenuTrigger",
  "Popover",
  "PopoverClose",
  "PopoverContent",
  "PopoverCreateHandle",
  "PopoverDescription",
  "PopoverPopup",
  "PopoverTitle",
  "PopoverTrigger",
  "ProviderModelPicker",
  "RegistryContext",
  "RegistryProvider",
  "ScrollArea",
  "ScrollBar",
  "Select",
  "SelectButton",
  "SelectContent",
  "SelectGroup",
  "SelectGroupLabel",
  "SelectItem",
  "SelectPopup",
  "SelectSeparator",
  "SelectTrigger",
  "SelectValue",
  "Separator",
  "Sheet",
  "SheetBackdrop",
  "SheetClose",
  "SheetContent",
  "SheetDescription",
  "SheetFooter",
  "SheetHeader",
  "SheetOverlay",
  "SheetPanel",
  "SheetPopup",
  "SheetPortal",
  "SheetTitle",
  "SheetTrigger",
  "Sidebar",
  "SidebarContent",
  "SidebarFooter",
  "SidebarGroup",
  "SidebarGroupAction",
  "SidebarGroupContent",
  "SidebarGroupLabel",
  "SidebarHeader",
  "SidebarInput",
  "SidebarInset",
  "SidebarMenu",
  "SidebarMenuAction",
  "SidebarMenuBadge",
  "SidebarMenuButton",
  "SidebarMenuItem",
  "SidebarMenuSkeleton",
  "SidebarMenuSub",
  "SidebarMenuSubButton",
  "SidebarMenuSubItem",
  "SidebarProvider",
  "SidebarRail",
  "SidebarSeparator",
  "SidebarTrigger",
  "Spinner",
  "Switch",
  "Textarea",
  "ToastProvider",
  "Tooltip",
  "TooltipCreateHandle",
  "TooltipPopup",
  "TooltipProvider",
  "TooltipTrigger",
  "TraitsMenuContent",
  "TraitsPicker",
  "TypeId",
  "anchoredToastManager",
  "AsyncResult",
  "Atom",
  "AtomRegistry",
  "badgeVariants",
  "buttonVariants",
  "createPluginAtoms",
  "defineWebPlugin",
  "getAppAtomRegistry",
  "getConnectionAtomRuntime",
  "hostCompat",
  "isPluginSdkWebExternal",
  "make",
  "pluginSdkWebExternalDependencies",
  "scheduleTask",
  "selectTriggerVariants",
  "shouldRenderTraitsControls",
  "stackedThreadToast",
  "toastManager",
  "useAtom",
  "useAtomCommand",
  "useAtomInitialValues",
  "useAtomMount",
  "useAtomQueryRunner",
  "useAtomRef",
  "useAtomRefProp",
  "useAtomRefPropValue",
  "useAtomRefresh",
  "useAtomSet",
  "useAtomSubscribe",
  "useAtomSuspense",
  "useAtomValue",
  "useSidebar",
  "useSidebarVisibility",
] as const;

export const pluginHostShimExportNames = {
  react: reactExports,
  "react-dom": reactDomExports,
  "react-dom/client": reactDomClientExports,
  "react/jsx-runtime": jsxRuntimeExports,
  "react/jsx-dev-runtime": jsxDevRuntimeExports,
  "@effect/atom-react": atomReactExports,
  effect: effectExports,
  "@t3tools/plugin-sdk-web": pluginSdkWebExports,
} satisfies Record<PluginHostModuleSpecifier, ReadonlyArray<string>>;

export function pluginHostModulePath(moduleName: PluginHostModuleSpecifier): string {
  return pluginHostImportMap.imports[moduleName].slice("/plugin-host/".length);
}

export function pluginHostModuleFromPath(pathname: string): PluginHostModuleSpecifier | null {
  if (!pathname.endsWith(".js")) return null;
  const moduleName = pathname.slice(0, -".js".length);
  return pluginHostModuleSpecifiers.includes(moduleName as PluginHostModuleSpecifier)
    ? (moduleName as PluginHostModuleSpecifier)
    : null;
}

export function getPluginHostShimSource(moduleName: PluginHostModuleSpecifier): string {
  const exportLines = pluginHostShimExportNames[moduleName]
    .map((name) => `export const ${name} = m.${name};`)
    .join("\n");
  return [
    `const m = globalThis.__T3_PLUGIN_HOST__[${JSON.stringify(moduleName)}];`,
    `if (!m) throw new Error(${JSON.stringify(`T3 plugin host module ${moduleName} is not ready.`)});`,
    "export default m.default ?? m;",
    exportLines,
    "",
  ].join("\n");
}

export const pluginHostBootstrapSource = `
const readyKey = "__T3_PLUGIN_HOST_READY__";
const resolveKey = "__T3_PLUGIN_HOST_READY_RESOLVE__";
if (!globalThis[readyKey]) {
  globalThis[readyKey] = new Promise((resolve) => {
    globalThis[resolveKey] = resolve;
  });
}
if (globalThis.__T3_PLUGIN_HOST__) {
  globalThis[resolveKey]?.(globalThis.__T3_PLUGIN_HOST__);
}
`.trim();

export function buildPluginHostHeadInjection(): string {
  const importMapJson = JSON.stringify(pluginHostImportMap);
  return [
    "<!-- t3-plugin-host:start -->",
    `<script type="importmap" ${PLUGIN_HOST_IMPORT_MAP_MARKER}>${importMapJson}</script>`,
    `<script type="module" ${PLUGIN_HOST_BOOTSTRAP_MARKER}>${pluginHostBootstrapSource}</script>`,
    "<!-- t3-plugin-host:end -->",
  ].join("\n");
}

export function injectPluginHostHeadHtml(html: string): string {
  if (html.includes(PLUGIN_HOST_IMPORT_MAP_MARKER)) {
    return html;
  }
  const injection = `\n${buildPluginHostHeadInjection()}\n`;
  const headCloseMatch = /<\/head\s*>/iu.exec(html);
  if (!headCloseMatch || headCloseMatch.index === undefined) {
    return `${injection}${html}`;
  }
  return `${html.slice(0, headCloseMatch.index)}${injection}${html.slice(headCloseMatch.index)}`;
}
