import Foundation

/// Curated, geographically diverse places used by the built-in World scenery set.
///
/// Keep names suitable for thread titles and queries specific enough that Unsplash
/// returns the actual place rather than a generic photo from the surrounding country.
enum WorldSceneryCatalog {
    static let locations: [SceneryLocation] = [
        // Europe
        .init(name: "Santorini, Greece", query: "santorini greece caldera"),
        .init(name: "Tre Cime, Italy", query: "tre cime dolomites italy"),
        .init(name: "Lofoten, Norway", query: "lofoten islands norway"),
        .init(name: "Zermatt, Switzerland", query: "matterhorn zermatt switzerland"),
        .init(name: "Skógafoss, Iceland", query: "skogafoss waterfall iceland"),
        .init(name: "Cappadocia, Türkiye", query: "cappadocia turkey balloons"),
        .init(name: "Plitvice Lakes, Croatia", query: "plitvice lakes croatia"),
        .init(name: "Isle of Skye, United Kingdom", query: "isle of skye scotland"),
        .init(name: "Lake Bled, Slovenia", query: "lake bled slovenia"),
        .init(name: "Sete Cidades, Portugal", query: "sete cidades azores portugal"),
        .init(name: "Hallstatt, Austria", query: "hallstatt austria lake mountains"),
        .init(name: "Saxon Switzerland, Germany", query: "saxon switzerland germany bastion bridge"),
        .init(name: "Mont Saint-Michel, France", query: "mont saint michel france"),
        .init(name: "Geirangerfjord, Norway", query: "geirangerfjord norway"),
        .init(name: "Faroe Islands, Denmark", query: "faroe islands waterfall village"),
        .init(name: "Cliffs of Moher, Ireland", query: "cliffs of moher ireland"),
        .init(name: "Kirkjufell, Iceland", query: "kirkjufell mountain iceland"),
        .init(name: "Seceda, Italy", query: "seceda dolomites italy"),
        .init(name: "Lauterbrunnen, Switzerland", query: "lauterbrunnen valley switzerland"),
        .init(name: "Prokletije, Albania", query: "prokletije albanian alps"),
        .init(name: "Kotor Bay, Montenegro", query: "kotor bay montenegro"),
        .init(name: "Meteora, Greece", query: "meteora monasteries greece"),
        .init(name: "Picos de Europa, Spain", query: "picos de europa spain mountains"),
        .init(name: "Benagil Cave, Portugal", query: "benagil cave algarve portugal"),
        .init(name: "Étretat, France", query: "etretat cliffs normandy france"),
        .init(name: "Sveti Stefan, Montenegro", query: "sveti stefan montenegro"),
        .init(name: "Rila Lakes, Bulgaria", query: "seven rila lakes bulgaria"),
        .init(name: "Transfăgărășan, Romania", query: "transfagarasan road romania mountains"),
        .init(name: "Český Krumlov, Czechia", query: "cesky krumlov czech republic"),
        .init(name: "Białowieża Forest, Poland", query: "bialowieza forest poland"),
        .init(name: "Curonian Spit, Lithuania", query: "curonian spit lithuania dunes"),
        .init(name: "Gauja Valley, Latvia", query: "gauja national park latvia autumn"),
        .init(name: "Saaremaa, Estonia", query: "saaremaa estonia coast"),
        .init(name: "Lapland, Finland", query: "finnish lapland aurora cabin"),
        .init(name: "Abisko, Sweden", query: "abisko sweden northern lights"),
        .init(name: "Senja, Norway", query: "senja norway mountains ocean"),
        .init(name: "Giant's Causeway, United Kingdom", query: "giants causeway northern ireland"),
        .init(name: "Snowdonia, United Kingdom", query: "snowdonia wales mountains lake"),
        .init(name: "Calanques, France", query: "calanques cassis france turquoise"),
        .init(name: "Lake Königssee, Germany", query: "konigssee bavaria germany lake"),
        .init(name: "Grossglockner, Austria", query: "grossglockner austria alpine road"),
        .init(name: "Soča Valley, Slovenia", query: "soca river valley slovenia"),
        .init(name: "Hvar, Croatia", query: "hvar croatia adriatic"),
        .init(name: "Durmitor, Montenegro", query: "durmitor national park montenegro"),
        .init(name: "Mostar, Bosnia and Herzegovina", query: "mostar old bridge bosnia"),
        .init(name: "Ohrid, North Macedonia", query: "lake ohrid north macedonia"),
        .init(name: "Lofou, Cyprus", query: "lofou village cyprus stone"),
        .init(name: "Gozo, Malta", query: "gozo malta coast"),
        .init(name: "Vík, Iceland", query: "vik iceland black sand beach"),
        .init(name: "Madeira, Portugal", query: "madeira portugal mountain coast"),

        // Asia and the Middle East
        .init(name: "Kyoto, Japan", query: "kyoto japan temple"),
        .init(name: "Petra, Jordan", query: "petra jordan treasury"),
        .init(name: "Zhangjiajie, China", query: "zhangjiajie china mountains"),
        .init(name: "Ha Long Bay, Vietnam", query: "ha long bay vietnam"),
        .init(name: "El Nido, Philippines", query: "el nido palawan philippines"),
        .init(name: "Ubud, Indonesia", query: "tegalalang rice terrace bali indonesia"),
        .init(name: "Mount Fuji, Japan", query: "mount fuji japan lake cherry blossoms"),
        .init(name: "Arashiyama, Japan", query: "arashiyama bamboo forest kyoto"),
        .init(name: "Shirakawa-go, Japan", query: "shirakawa go japan winter village"),
        .init(name: "Jeju Island, South Korea", query: "jeju island south korea coast"),
        .init(name: "Seoraksan, South Korea", query: "seoraksan south korea autumn"),
        .init(name: "Guilin, China", query: "guilin china karst li river"),
        .init(name: "Jiuzhaigou, China", query: "jiuzhaigou china turquoise lake"),
        .init(name: "Yuanyang, China", query: "yuanyang rice terraces china"),
        .init(name: "Tiger's Nest, Bhutan", query: "tigers nest monastery bhutan"),
        .init(name: "Punakha, Bhutan", query: "punakha dzong bhutan"),
        .init(name: "Annapurna, Nepal", query: "annapurna nepal himalaya"),
        .init(name: "Everest Base Camp, Nepal", query: "everest base camp nepal himalaya"),
        .init(name: "Pangong Lake, India", query: "pangong lake ladakh india"),
        .init(name: "Valley of Flowers, India", query: "valley of flowers uttarakhand india"),
        .init(name: "Munnar, India", query: "munnar kerala india tea plantations"),
        .init(name: "Hampi, India", query: "hampi india ruins landscape"),
        .init(name: "Sigiriya, Sri Lanka", query: "sigiriya rock sri lanka"),
        .init(name: "Ella, Sri Lanka", query: "ella sri lanka nine arches bridge"),
        .init(name: "Bagan, Myanmar", query: "bagan myanmar temples sunrise"),
        .init(name: "Inle Lake, Myanmar", query: "inle lake myanmar"),
        .init(name: "Luang Prabang, Laos", query: "luang prabang laos waterfall"),
        .init(name: "Angkor Wat, Cambodia", query: "angkor wat cambodia sunrise"),
        .init(name: "Ninh Bình, Vietnam", query: "ninh binh vietnam limestone river"),
        .init(name: "Hội An, Vietnam", query: "hoi an vietnam lanterns"),
        .init(name: "Khao Sok, Thailand", query: "khao sok thailand lake limestone"),
        .init(name: "Railay Beach, Thailand", query: "railay beach thailand cliffs"),
        .init(name: "Komodo, Indonesia", query: "komodo island indonesia pink beach"),
        .init(name: "Mount Bromo, Indonesia", query: "mount bromo indonesia sunrise"),
        .init(name: "Raja Ampat, Indonesia", query: "raja ampat indonesia islands"),
        .init(name: "Banaue, Philippines", query: "banaue rice terraces philippines"),
        .init(name: "Chocolate Hills, Philippines", query: "chocolate hills bohol philippines"),
        .init(name: "Mount Kinabalu, Malaysia", query: "mount kinabalu malaysia"),
        .init(name: "Cameron Highlands, Malaysia", query: "cameron highlands malaysia tea"),
        .init(name: "Gardens by the Bay, Singapore", query: "gardens by the bay singapore night"),
        .init(name: "Wadi Rum, Jordan", query: "wadi rum jordan desert"),
        .init(name: "Socotra, Yemen", query: "socotra yemen dragon blood trees"),
        .init(name: "Musandam, Oman", query: "musandam oman fjords"),
        .init(name: "AlUla, Saudi Arabia", query: "alula saudi arabia desert rocks"),
        .init(name: "Sheikh Zayed Mosque, United Arab Emirates", query: "sheikh zayed mosque abu dhabi"),
        .init(name: "Hormuz Island, Iran", query: "hormuz island iran colorful mountains"),
        .init(name: "Cappadocia Valleys, Türkiye", query: "cappadocia turkey rock formations sunrise"),
        .init(name: "Lake Sevan, Armenia", query: "lake sevan armenia monastery"),
        .init(name: "Kazbegi, Georgia", query: "kazbegi georgia caucasus church"),
        .init(name: "Gobustan, Azerbaijan", query: "gobustan azerbaijan mud volcano"),
        .init(name: "Charyn Canyon, Kazakhstan", query: "charyn canyon kazakhstan"),
        .init(name: "Song-Kul, Kyrgyzstan", query: "song kul lake kyrgyzstan yurts"),
        .init(name: "Pamir Highway, Tajikistan", query: "pamir highway tajikistan mountains"),
        .init(name: "Registan, Uzbekistan", query: "registan samarkand uzbekistan"),
        .init(name: "Darvaza, Turkmenistan", query: "darvaza gas crater turkmenistan"),
        .init(name: "Gobi Desert, Mongolia", query: "gobi desert mongolia dunes camels"),
        .init(name: "Altai Mountains, Mongolia", query: "altai mountains mongolia"),
        .init(name: "Tian Shan, Kyrgyzstan", query: "tian shan kyrgyzstan mountains lake"),
        .init(name: "Hunza Valley, Pakistan", query: "hunza valley pakistan mountains"),
        .init(name: "Fairy Meadows, Pakistan", query: "fairy meadows nanga parbat pakistan"),

        // Africa
        .init(name: "Sossusvlei, Namibia", query: "sossusvlei namibia dunes"),
        .init(name: "Merzouga, Morocco", query: "merzouga sahara morocco dunes"),
        .init(name: "Serengeti, Tanzania", query: "serengeti tanzania acacia sunset"),
        .init(name: "Ngorongoro, Tanzania", query: "ngorongoro crater tanzania"),
        .init(name: "Mount Kilimanjaro, Tanzania", query: "mount kilimanjaro tanzania"),
        .init(name: "Zanzibar, Tanzania", query: "zanzibar tanzania turquoise beach"),
        .init(name: "Maasai Mara, Kenya", query: "maasai mara kenya wildlife landscape"),
        .init(name: "Amboseli, Kenya", query: "amboseli kenya elephants kilimanjaro"),
        .init(name: "Diani Beach, Kenya", query: "diani beach kenya"),
        .init(name: "Bwindi Forest, Uganda", query: "bwindi forest uganda mist"),
        .init(name: "Volcanoes National Park, Rwanda", query: "volcanoes national park rwanda"),
        .init(name: "Simien Mountains, Ethiopia", query: "simien mountains ethiopia"),
        .init(name: "Danakil Depression, Ethiopia", query: "danakil depression ethiopia colors"),
        .init(name: "Lalibela, Ethiopia", query: "lalibela ethiopia rock church"),
        .init(name: "Okavango Delta, Botswana", query: "okavango delta botswana aerial"),
        .init(name: "Makgadikgadi, Botswana", query: "makgadikgadi salt pans botswana"),
        .init(name: "Victoria Falls, Zimbabwe", query: "victoria falls zimbabwe"),
        .init(name: "Mana Pools, Zimbabwe", query: "mana pools zimbabwe elephants"),
        .init(name: "Blyde River Canyon, South Africa", query: "blyde river canyon south africa"),
        .init(name: "Drakensberg, South Africa", query: "drakensberg south africa mountains"),
        .init(name: "Cape Point, South Africa", query: "cape point south africa coast"),
        .init(name: "Namaqualand, South Africa", query: "namaqualand south africa flowers"),
        .init(name: "Bazaruto, Mozambique", query: "bazaruto mozambique islands"),
        .init(name: "Avenue of the Baobabs, Madagascar", query: "avenue of baobabs madagascar"),
        .init(name: "Tsingy de Bemaraha, Madagascar", query: "tsingy de bemaraha madagascar"),
        .init(name: "Le Morne, Mauritius", query: "le morne mauritius aerial"),
        .init(name: "Anse Source d'Argent, Seychelles", query: "anse source argent seychelles"),
        .init(name: "Pico do Fogo, Cabo Verde", query: "pico do fogo cape verde volcano"),
        .init(name: "Chefchaouen, Morocco", query: "chefchaouen morocco blue city"),
        .init(name: "Atlas Mountains, Morocco", query: "atlas mountains morocco village"),

        // North America, Central America, and the Caribbean
        .init(name: "Moraine Lake, Canada", query: "moraine lake banff canada"),
        .init(name: "Arenal, Costa Rica", query: "arenal volcano costa rica"),
        .init(name: "Yosemite Valley, United States", query: "yosemite valley california"),
        .init(name: "Grand Canyon, United States", query: "grand canyon arizona sunrise"),
        .init(name: "Monument Valley, United States", query: "monument valley arizona utah"),
        .init(name: "Na Pali Coast, United States", query: "na pali coast kauai hawaii"),
        .init(name: "Denali, United States", query: "denali alaska mountain"),
        .init(name: "Glacier Bay, United States", query: "glacier bay alaska"),
        .init(name: "Antelope Canyon, United States", query: "antelope canyon arizona light"),
        .init(name: "Maroon Bells, United States", query: "maroon bells colorado autumn"),
        .init(name: "Yellowstone, United States", query: "yellowstone grand prismatic spring"),
        .init(name: "Big Sur, United States", query: "big sur california coast"),
        .init(name: "Mount Rainier, United States", query: "mount rainier washington wildflowers"),
        .init(name: "Crater Lake, United States", query: "crater lake oregon"),
        .init(name: "Bryce Canyon, United States", query: "bryce canyon utah sunrise"),
        .init(name: "Banff, Canada", query: "banff canada mountains lake"),
        .init(name: "Jasper, Canada", query: "jasper national park canada"),
        .init(name: "Tofino, Canada", query: "tofino vancouver island canada"),
        .init(name: "Gros Morne, Canada", query: "gros morne newfoundland canada"),
        .init(name: "Torngat Mountains, Canada", query: "torngat mountains canada"),
        .init(name: "Tulum, Mexico", query: "tulum mexico ruins turquoise sea"),
        .init(name: "Sumidero Canyon, Mexico", query: "sumidero canyon chiapas mexico"),
        .init(name: "Hierve el Agua, Mexico", query: "hierve el agua oaxaca mexico"),
        .init(name: "Lake Atitlán, Guatemala", query: "lake atitlan guatemala volcano"),
        .init(name: "Semuc Champey, Guatemala", query: "semuc champey guatemala pools"),
        .init(name: "Great Blue Hole, Belize", query: "great blue hole belize aerial"),
        .init(name: "Roatán, Honduras", query: "roatan honduras reef beach"),
        .init(name: "Cerro Negro, Nicaragua", query: "cerro negro volcano nicaragua"),
        .init(name: "Monteverde, Costa Rica", query: "monteverde cloud forest costa rica"),
        .init(name: "Bocas del Toro, Panama", query: "bocas del toro panama islands"),
        .init(name: "Viñales, Cuba", query: "vinales cuba valley"),
        .init(name: "Samaná, Dominican Republic", query: "samana dominican republic coast"),
        .init(name: "El Yunque, Puerto Rico", query: "el yunque puerto rico rainforest"),
        .init(name: "Pitons, Saint Lucia", query: "pitons saint lucia"),
        .init(name: "The Baths, British Virgin Islands", query: "the baths virgin gorda"),

        // South America
        .init(name: "Torres del Paine, Chile", query: "torres del paine patagonia chile"),
        .init(name: "Machu Picchu, Peru", query: "machu picchu peru"),
        .init(name: "Iguazu Falls, Argentina", query: "iguazu falls argentina"),
        .init(name: "Salar de Uyuni, Bolivia", query: "salar de uyuni bolivia reflection"),
        .init(name: "Lençóis Maranhenses, Brazil", query: "lencois maranhenses brazil lagoons"),
        .init(name: "Rio de Janeiro, Brazil", query: "rio de janeiro brazil sugarloaf"),
        .init(name: "Chapada Diamantina, Brazil", query: "chapada diamantina brazil"),
        .init(name: "Fernando de Noronha, Brazil", query: "fernando de noronha brazil aerial"),
        .init(name: "Mount Roraima, Venezuela", query: "mount roraima venezuela"),
        .init(name: "Angel Falls, Venezuela", query: "angel falls venezuela"),
        .init(name: "Cocora Valley, Colombia", query: "cocora valley colombia wax palms"),
        .init(name: "Caño Cristales, Colombia", query: "cano cristales colombia river"),
        .init(name: "Galápagos, Ecuador", query: "galapagos ecuador landscape"),
        .init(name: "Cotopaxi, Ecuador", query: "cotopaxi ecuador volcano"),
        .init(name: "Huacachina, Peru", query: "huacachina peru oasis dunes"),
        .init(name: "Rainbow Mountain, Peru", query: "rainbow mountain peru"),
        .init(name: "Laguna Colorada, Bolivia", query: "laguna colorada bolivia flamingos"),
        .init(name: "Atacama Desert, Chile", query: "atacama desert chile night sky"),
        .init(name: "Marble Caves, Chile", query: "marble caves patagonia chile"),
        .init(name: "Perito Moreno, Argentina", query: "perito moreno glacier argentina"),
        .init(name: "Fitz Roy, Argentina", query: "fitz roy patagonia argentina"),
        .init(name: "Punta del Este, Uruguay", query: "punta del este uruguay coast"),
        .init(name: "Kaieteur Falls, Guyana", query: "kaieteur falls guyana"),
        .init(name: "Central Suriname Reserve, Suriname", query: "suriname rainforest river"),
        .init(name: "Los Roques, Venezuela", query: "los roques venezuela islands"),

        // Oceania and remote islands
        .init(name: "Milford Sound, New Zealand", query: "milford sound new zealand"),
        .init(name: "Aoraki, New Zealand", query: "aoraki mount cook new zealand"),
        .init(name: "Lake Tekapo, New Zealand", query: "lake tekapo new zealand lupins"),
        .init(name: "Tongariro, New Zealand", query: "tongariro alpine crossing new zealand"),
        .init(name: "Roy's Peak, New Zealand", query: "roys peak wanaka new zealand"),
        .init(name: "Cathedral Cove, New Zealand", query: "cathedral cove new zealand"),
        .init(name: "Great Barrier Reef, Australia", query: "great barrier reef australia aerial"),
        .init(name: "Uluru, Australia", query: "uluru australia sunset"),
        .init(name: "Twelve Apostles, Australia", query: "twelve apostles australia coast"),
        .init(name: "Whitehaven Beach, Australia", query: "whitehaven beach australia aerial"),
        .init(name: "Cradle Mountain, Australia", query: "cradle mountain tasmania australia"),
        .init(name: "Kakadu, Australia", query: "kakadu australia wetlands"),
        .init(name: "Bora Bora, French Polynesia", query: "bora bora french polynesia aerial"),
        .init(name: "Moorea, French Polynesia", query: "moorea french polynesia mountains"),
        .init(name: "Aitutaki, Cook Islands", query: "aitutaki cook islands lagoon"),
        .init(name: "Yasawa Islands, Fiji", query: "yasawa islands fiji"),
        .init(name: "Savai'i, Samoa", query: "savaii samoa waterfall coast"),
        .init(name: "Vavaʻu, Tonga", query: "vavau tonga islands"),
        .init(name: "Espiritu Santo, Vanuatu", query: "espiritu santo vanuatu blue hole"),
        .init(name: "Rock Islands, Palau", query: "rock islands palau aerial"),
        .init(name: "Kokoda Track, Papua New Guinea", query: "kokoda track papua new guinea mountains"),
        .init(name: "Easter Island, Chile", query: "easter island chile moai"),
        .init(name: "Lord Howe Island, Australia", query: "lord howe island australia"),
        .init(name: "Norfolk Island, Australia", query: "norfolk island australia coast"),
    ]
}
