#!/usr/bin/env bash
set -euo pipefail

# Set up local .test domains with Caddy + mkcert for HTTPS development.
#
# Prerequisites:
#   brew install caddy mkcert
#   mkcert -install   (once, installs local CA)
#
# Usage:
#   ./scripts/setup-domain.sh app --app-port 12000 --api-port 12001
#   ./scripts/setup-domain.sh myproject --app-port 12100 --api-port 12101

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
CHECK_PORT_POLICY_SCRIPT="$SCRIPT_DIR/check-port-policy.sh"

APP_NAME="app"
APP_PORT=""
API_PORT=""
DRY_RUN=false
CADDYFILE_PATH=".local/Caddyfile"
CERT_DIR=".local/certs"

usage() {
  cat <<'EOF'
Set up local .test domains with Caddy + mkcert for HTTPS development.

Usage:
  bash scripts/setup-domain.sh [app-name] --app-port <port> --api-port <port> [--dry-run]

Options:
  --app-port <port>   Explicit app/web port (must be >= 10000)
  --api-port <port>   Explicit API port (must be >= 10000 and unique)
  --caddyfile <path>  Output path for the generated Caddyfile (default: .local/Caddyfile)
  --dry-run           Validate inputs and print the generated config without touching hosts/certs
  -h, --help          Show this help
EOF
}

require_commands() {
  local cmd=""
  for cmd in caddy mkcert; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
      echo "Error: $cmd is required." >&2
      echo "Install: brew install caddy mkcert && mkcert -install" >&2
      exit 1
    fi
  done
}

render_caddyfile() {
  cat <<EOF
# Local development — generated by scripts/setup-domain.sh
# Do not commit this file if it contains project-specific ports.

${BASE_DOMAIN} {
  tls ${CERT_DIR}/${BASE_DOMAIN}.pem ${CERT_DIR}/${BASE_DOMAIN}-key.pem
  reverse_proxy localhost:${APP_PORT}
}

${API_DOMAIN} {
  tls ${CERT_DIR}/${BASE_DOMAIN}.pem ${CERT_DIR}/${BASE_DOMAIN}-key.pem
  reverse_proxy localhost:${API_PORT}
}
EOF
}

ensure_hosts_entry() {
  local domain="$1"
  if ! grep -Fxq "127.0.0.1 $domain" /etc/hosts; then
    echo "127.0.0.1 $domain" | sudo tee -a /etc/hosts >/dev/null
    echo "  Added $domain to /etc/hosts"
    return
  fi

  echo "  $domain already in /etc/hosts"
}

if [[ "${1:-}" != "" && "${1:-}" != --* ]]; then
  APP_NAME="$1"
  shift
fi

while [[ $# -gt 0 ]]; do
  case "$1" in
    --app-port)
      if [[ -z "${2:-}" || "${2:-}" == --* ]]; then
        echo "Error: --app-port requires a port value." >&2
        usage
        exit 1
      fi
      APP_PORT="$2"
      shift 2
      ;;
    --api-port)
      if [[ -z "${2:-}" || "${2:-}" == --* ]]; then
        echo "Error: --api-port requires a port value." >&2
        usage
        exit 1
      fi
      API_PORT="$2"
      shift 2
      ;;
    --caddyfile)
      if [[ -z "${2:-}" || "${2:-}" == --* ]]; then
        echo "Error: --caddyfile requires a path." >&2
        usage
        exit 1
      fi
      CADDYFILE_PATH="$2"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Error: unknown argument '$1'." >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "$APP_PORT" || -z "$API_PORT" ]]; then
  echo "Error: both --app-port and --api-port are required." >&2
  usage
  exit 1
fi

if [[ ! -r "$CHECK_PORT_POLICY_SCRIPT" ]]; then
  echo "Error: missing readable port policy checker at $CHECK_PORT_POLICY_SCRIPT." >&2
  exit 1
fi

bash "$CHECK_PORT_POLICY_SCRIPT" \
  --port "app=${APP_PORT}" \
  --port "api=${API_PORT}"

BASE_DOMAIN="${APP_NAME}.test"
API_DOMAIN="api.${BASE_DOMAIN}"

if [[ "$DRY_RUN" == true ]]; then
  echo "[setup-domain] dry run for ${BASE_DOMAIN} using app=${APP_PORT} api=${API_PORT}"
  render_caddyfile
  exit 0
fi

require_commands

echo "Setting up local domains: $BASE_DOMAIN, $API_DOMAIN"

for domain in "$BASE_DOMAIN" "$API_DOMAIN"; do
  ensure_hosts_entry "$domain"
done

mkdir -p "$CERT_DIR" "$(dirname -- "$CADDYFILE_PATH")"
mkcert -cert-file "$CERT_DIR/${BASE_DOMAIN}.pem" \
       -key-file "$CERT_DIR/${BASE_DOMAIN}-key.pem" \
       "$BASE_DOMAIN" "$API_DOMAIN"

render_caddyfile > "$CADDYFILE_PATH"

echo ""
echo "Done. Start Caddy: caddy run --config $CADDYFILE_PATH"
echo ""
echo "Domains:"
echo "  https://${BASE_DOMAIN}   → localhost:${APP_PORT} (apps/web or apps/www)"
echo "  https://${API_DOMAIN}    → localhost:${API_PORT} (apps/api)"
echo ""
echo "Set in environment:"
echo "  BETTER_AUTH_URL=https://${API_DOMAIN}"
echo "  APP_URL=https://${BASE_DOMAIN}"
