import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type PackageJson = {
  name?: string;
  scripts?: Record<string, string>;
};

const currentDir = dirname(fileURLToPath(import.meta.url));

const generatedNotice = "# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY";

const optionValue = (name: string): string | null => {
  const index = process.argv.indexOf(name);
  if (index === -1) {
    return null;
  }

  return process.argv[index + 1] ?? null;
};

const readPackageJson = (repoRoot: string): PackageJson =>
  JSON.parse(readFileSync(join(repoRoot, "package.json"), "utf8")) as PackageJson;

const tomlString = (value: string): string => JSON.stringify(value);

const actionIcon = (scriptName: string): string => {
  if (scriptName === "dev" || scriptName.startsWith("dev:")) {
    return "play";
  }

  return "tool";
};

const actionName = (scriptName: string): string => {
  const labels: Record<string, string> = {
    check: "Check",
    typecheck: "Typecheck",
    lint: "Lint",
    test: "Test",
    preflight: "Preflight",
    "codex:sync": "Codex Sync",
    "codex:check": "Codex Check",
    "plan:lint": "Plan Lint",
    "validate:local": "Validate Local",
    "pr:check": "PR Check",
    "rwx:sync": "RWX Sync",
    "rwx:check": "RWX Check",
    "adopt:check": "Adoption Check",
    build: "Build",
    dev: "Run All",
  };

  return labels[scriptName] ?? scriptName;
};

export const codexEnvironmentForPackage = (pkg: PackageJson): string => {
  const scripts = Object.keys(pkg.scripts ?? {});
  const actions = scripts
    .map((scriptName) =>
      [
        "[[actions]]",
        `name = ${tomlString(actionName(scriptName))}`,
        `icon = ${tomlString(actionIcon(scriptName))}`,
        `command = ${tomlString(`bun run ${scriptName}`)}`,
        "",
      ].join("\n"),
    )
    .join("\n");

  return [
    generatedNotice,
    "version = 1",
    `name = ${tomlString(pkg.name ?? "codex-workspace")}`,
    "",
    "[setup]",
    'script = ""',
    "",
    "[setup.darwin]",
    "script = '''",
    'cd "$CODEX_WORKTREE_PATH"',
    "",
    "bun install --frozen-lockfile",
    "bun rwx:check",
    "bun codex:check",
    "'''",
    "",
    "[cleanup]",
    'script = ""',
    "",
    "[cleanup.darwin]",
    "script = '''",
    'cd "$CODEX_WORKTREE_PATH"',
    "",
    "rm -rf .local/tmp .cache/tmp",
    "'''",
    "",
    actions.trimEnd(),
    "",
  ].join("\n");
};

const syncEnvironment = (repoRoot: string, checkOnly: boolean): string[] => {
  const codexEnvironmentPath = join(repoRoot, ".codex", "environments", "environment.toml");
  const packageJsonPath = join(repoRoot, "package.json");

  if (!existsSync(packageJsonPath)) {
    return [`${packageJsonPath} does not exist.`];
  }

  const expected = codexEnvironmentForPackage(readPackageJson(repoRoot));
  const actual = existsSync(codexEnvironmentPath)
    ? readFileSync(codexEnvironmentPath, "utf8")
    : null;

  if (actual === expected) {
    return [];
  }

  if (checkOnly) {
    return [
      `${codexEnvironmentPath} is out of sync with package.json scripts. Run bun codex:sync.`,
    ];
  }

  mkdirSync(dirname(codexEnvironmentPath), { recursive: true });
  writeFileSync(codexEnvironmentPath, expected);
  return [];
};

const main = (): void => {
  const checkOnly = process.argv.includes("--check");
  const targetRoot = optionValue("--target");
  const repoRoot = targetRoot === null ? resolve(currentDir, "..") : resolve(targetRoot);
  const errors = syncEnvironment(repoRoot, checkOnly);

  if (errors.length > 0) {
    for (const error of errors) {
      console.error(error);
    }
    process.exit(1);
  }

  const mode = checkOnly ? "checked" : "synced";
  console.log(`[codex-environment] OK: environment ${mode}.`);
};

if (import.meta.main) {
  main();
}
