import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type CommandMetadata = {
  name: string;
  description: string;
  argumentHint: string;
};

const currentDir = dirname(fileURLToPath(import.meta.url));

const generatedNotice =
  "<!-- GENERATED by scripts/sync-codex-commands.ts. Do not edit by hand. -->";

const optionValue = (name: string): string | null => {
  const index = process.argv.indexOf(name);
  if (index === -1) {
    return null;
  }

  return process.argv[index + 1] ?? null;
};

const parseFrontmatterValue = (text: string, key: string): string => {
  const match = new RegExp(`^${key}:\\s*(.+)$`, "m").exec(text);
  return match?.[1]?.trim() ?? "";
};

const commandFiles = (claudeCommandsDir: string): string[] =>
  readdirSync(claudeCommandsDir)
    .filter((name) => name.endsWith(".md"))
    .sort();

const commandMetadata = (claudeCommandsDir: string, filename: string): CommandMetadata => {
  const name = filename.replace(/\.md$/, "");
  const text = readFileSync(join(claudeCommandsDir, filename), "utf8");

  return {
    name,
    description:
      parseFrontmatterValue(text, "description") ||
      `Run /${name} using the canonical Claude command runbook.`,
    argumentHint: parseFrontmatterValue(text, "argument-hint"),
  };
};

const wrapperFor = (metadata: CommandMetadata): string => {
  const argumentHintLine = metadata.argumentHint
    ? `argument-hint: ${JSON.stringify(metadata.argumentHint)}\n`
    : "";

  return `${generatedNotice}
---
description: ${JSON.stringify(metadata.description)}
${argumentHintLine}---

# /${metadata.name} for Codex

Canonical runbook: \`.claude/commands/${metadata.name}.md\`

When the user invokes \`/${metadata.name}\` in Codex, treat the text after the
command name as \`$ARGUMENTS\`, read the canonical runbook above, and execute the
same workflow from this repository root.

Rules:
- Follow \`AGENTS.md\` first, then the canonical command runbook.
- Preserve the command's existing branch, GitHub, validation, and safety gates.
- Do not edit this generated wrapper directly. Update the canonical
  \`.claude/commands/${metadata.name}.md\` file, then run \`bun codex:sync\`.
`;
};

const readIfExists = (filePath: string): string | null =>
  existsSync(filePath) ? readFileSync(filePath, "utf8") : null;

const syncCommands = (repoRoot: string, checkOnly: boolean): string[] => {
  const errors: string[] = [];
  const claudeCommandsDir = join(repoRoot, ".claude", "commands");
  const codexCommandsDir = join(repoRoot, ".codex", "commands");

  if (!existsSync(claudeCommandsDir)) {
    return [`${claudeCommandsDir} does not exist.`];
  }

  if (!existsSync(codexCommandsDir)) {
    if (checkOnly) {
      return [`${codexCommandsDir} does not exist. Run bun codex:sync.`];
    }
    mkdirSync(codexCommandsDir, { recursive: true });
  }

  const expectedFiles = new Set(commandFiles(claudeCommandsDir).map((filename) => filename));

  for (const filename of expectedFiles) {
    const metadata = commandMetadata(claudeCommandsDir, filename);
    const expected = wrapperFor(metadata);
    const target = join(codexCommandsDir, filename);
    const actual = readIfExists(target);

    if (actual !== expected) {
      if (checkOnly) {
        errors.push(`${target} is out of sync with .claude/commands/${filename}`);
      } else {
        writeFileSync(target, expected);
      }
    }
  }

  for (const filename of readdirSync(codexCommandsDir)
    .filter((name) => name.endsWith(".md"))
    .toSorted()) {
    if (!expectedFiles.has(filename)) {
      const target = join(codexCommandsDir, filename);
      if (checkOnly) {
        errors.push(`${target} has no matching .claude command`);
      } else {
        rmSync(target);
      }
    }
  }

  return errors;
};

const main = (): void => {
  const checkOnly = process.argv.includes("--check");
  const targetRoot = optionValue("--target");
  const repoRoot = targetRoot === null ? resolve(currentDir, "..") : resolve(targetRoot);
  const errors = syncCommands(repoRoot, checkOnly);

  if (errors.length > 0) {
    for (const error of errors) {
      console.error(error);
    }
    process.exit(1);
  }

  const mode = checkOnly ? "checked" : "synced";
  console.log(
    `[codex-commands] OK: ${commandFiles(join(repoRoot, ".claude", "commands")).length} command wrapper(s) ${mode}.`,
  );
};

main();
